Repository trimble-oss/modus-web-components, pull requests merged in 2023-08, with the labels that each got.

#1585 Fix console errors in Modus date picker
  stencil-workspace/src/components/modus-date-picker/modus-date-picker.tsx
Labels: bug

#1592 Fix incorrect triggering of disabled button events in Modal
  stencil-workspace/src/components/modus-modal/modus-modal.e2e.ts
  stencil-workspace/src/components/modus-modal/modus-modal.tsx
  stencil-workspace/storybook/stories/components/modus-modal/modus-modal.stories.tsx
Labels: bug

#1594 Modus Cards - Remove `backgroundColor` prop and encourage using CSS variable `--modus-card-bg`
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-card/modus-card.e2e.ts
  stencil-workspace/src/components/modus-card/modus-card.tsx
  stencil-workspace/src/components/modus-card/readme.md
  stencil-workspace/storybook/stories/components/modus-card/modus-card-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-card/modus-card.stories.tsx
Labels: bug, breaking-change

#1595 Fix Modus Content Tree UI issues with drag and drop
  stencil-workspace/src/components/modus-content-tree/modus-content-tree-drag-item.tsx
  stencil-workspace/src/components/modus-content-tree/modus-content-tree.constants.tsx
  stencil-workspace/src/components/modus-content-tree/modus-tree-view-item/modus-tree-view-item.tsx
  stencil-workspace/src/components/modus-content-tree/modus-tree-view/modus-tree-view.scss
  stencil-workspace/src/components/modus-content-tree/modus-tree-view/modus-tree-view.tsx
  stencil-workspace/storybook/stories/components/modus-content-tree/modus-content-tree.stories.tsx
Labels: bug

#1575 Modus Table - Added functionality for hyperlink
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-table/enums/index.ts
  stencil-workspace/src/components/modus-table/enums/modus-table-column-data-type.ts
  stencil-workspace/src/components/modus-table/models/modus-table-cell-link.ts
  stencil-workspace/src/components/modus-table/models/modus-table-column.ts
  stencil-workspace/src/components/modus-table/modus-table.scss
  stencil-workspace/src/components/modus-table/modus-table.tsx
  stencil-workspace/src/components/modus-table/modus-table.vars.scss
  stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-content.tsx
  stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-expand-icons.tsx
  stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-formatter.tsx
  stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-link-element.tsx
  stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell.tsx
  stencil-workspace/src/components/modus-table/parts/modus-table-summary-row.tsx
  stencil-workspace/src/components/modus-table/parts/panel/modus-table-dropdown-menu/modus-table-dropdown-menu.scss
  stencil-workspace/src/components/modus-table/readme.md
  stencil-workspace/src/global/themes.scss
  stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
Labels: table

#1587 Added functionality to make first column sticky
  stencil-workspace/src/components/modus-table/modus-table.scss
  stencil-workspace/src/components/modus-table/modus-table.tsx
  stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell.tsx
  stencil-workspace/src/components/modus-table/parts/header/modus-table-header.tsx
  stencil-workspace/src/components/modus-table/parts/modus-table-summary-row.tsx
Labels: table

#1607 Modus Date Picker Storybook page - Remove "under construction" warning message
  stencil-workspace/storybook/stories/components/modus-date-picker/modus-date-picker-storybook-docs.mdx
Labels: docs

#1616 Fixed the incorrect color code for Gray 10 and Trimble Gray
  stencil-workspace/src/global/themes.scss
Labels: bug, breaking-change

#1611 Fix Accessibility Errors on the User Input Components
  stencil-workspace/src/components/modus-date-input/modus-date-input.tsx
  stencil-workspace/src/components/modus-number-input/modus-number-input.tsx
  stencil-workspace/src/components/modus-select/modus-select.tsx
  stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
  stencil-workspace/src/components/modus-time-picker/modus-time-picker.tsx
  stencil-workspace/storybook/stories/components/modus-date-picker/modus-date-picker-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-date-picker/modus-date-picker.stories.tsx
  stencil-workspace/storybook/stories/components/modus-number-input/modus-number-input-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-number-input/modus-number-input.stories.tsx
  stencil-workspace/storybook/stories/components/modus-select/modus-select-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input.stories.tsx
  stencil-workspace/storybook/stories/components/modus-time-picker/modus-time-picker-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-time-picker/modus-time-picker.stories.tsx
Labels: bug, accessibility

#1635 Bump versions to v0.1.50
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: 1, skip-changelog

#1636 [NAV-220] show pointer when hovering in toast close icon
  stencil-workspace/src/components/modus-toast/modus-toast.scss
Labels: bug

#1639 Bump versions for React and Angular (v0.1.51)
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: 1, skip-changelog

#1657 bump version number for react/angular to v0.1.52
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: 1, skip-changelog

#1666 Use `<a>` for Navbar apps menu apps. Fix Navbar doc snippets
  stencil-workspace/src/components/modus-navbar/apps-menu/modus-navbar-apps-menu.scss
  stencil-workspace/src/components/modus-navbar/apps-menu/modus-navbar-apps-menu.tsx
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
Labels: bug

#1679 Minor dev deps update for React Workspace and Tests
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
  react-workspace/test-react-v17/package-lock.json
  react-workspace/test-react-v18/package-lock.json
  react-workspace/test-react-v18/package.json
Labels: 1, skip-changelog
