Repository trimble-oss/modus-web-components, pull requests merged in 2023-06, with the labels that each got.

#1371 Don't run Google Chat Notifications on Dependabot Alerts
  .github/workflows/google-chat-notifiy.yml
Labels: 1, skip-changelog

#1376 Added a few optional fields to the GitHub issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: skip-changelog

#1374 Make `category` and `showCategory` optional for Modus Navbar's apps menu
  stencil-workspace/src/components/modus-navbar/apps-menu/modus-navbar-apps-menu.tsx
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
Labels: 1, enhancement

#1379 Fix the breaking issues in GitHub Issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: skip-changelog

#1377 [NAV-110] fix issue with the height when the icons are not visible.
  stencil-workspace/src/components/modus-chip/modus-chip.scss
Labels: bug

#1366 Updated react workspace with latest MWC version
  react-workspace/.gitignore
  react-workspace/README.md
  react-workspace/package-lock.json
  react-workspace/package.json
  react-workspace/projects/test-react-v17/.gitignore
  react-workspace/projects/test-react-v17/README.md
  react-workspace/projects/test-react-v17/package-lock.json
  react-workspace/projects/test-react-v17/package.json
  react-workspace/projects/test-react-v17/public/index.html
  react-workspace/projects/test-react-v17/public/manifest.json
  react-workspace/projects/test-react-v17/src/App.css
  react-workspace/projects/test-react-v17/src/App.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusAccordionExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusAlertExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusAutoCompleteExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusBadgeExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusBreadcrumbExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusButtonExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusCardExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusCheckboxExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusChipExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusContentTreeExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusDataTableExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusDatePickerExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusDropdownExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusFileDropZoneExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusListExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusMessageExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusModalExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusNavbarExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusNumberInputExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusPaginationExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusProgressBarExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusRadioGroupExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusSelectExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusSideNavigationExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusSliderExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusSpinnerExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusSwitchExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusTabExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusTextInputExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusTimePickerExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusToastExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/ModusTooltipExamples.tsx
  react-workspace/projects/test-react-v17/src/examples/index.tsx
  react-workspace/projects/test-react-v17/src/index.tsx
  react-workspace/projects/test-react-v17/tsconfig.json
  react-workspace/src/index.ts
  react-workspace/tsconfig.json
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: react

#1385 Update package to v0.1.43
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#1392 Update React workspace for `@trimble-oss/modus-web-components-v0.1.43`
  CONTRIBUTING.md
  react-workspace/README.md
  react-workspace/package-lock.json
  react-workspace/package.json
  react-workspace/projects/test-react-v17/README.md
  react-workspace/projects/test-react-v17/package-lock.json
  react-workspace/projects/test-react-v17/package.json
  react-workspace/projects/test-react-v17/src/examples/ModusFileDropZoneExamples.tsx
Labels: react, skip-changelog

#1394 Update React Storybook page about the new Modus React Components library
  react-workspace/projects/test-react-v17/package-lock.json
  stencil-workspace/storybook/stories/framework-integrations/angular.stories.mdx
  stencil-workspace/storybook/stories/framework-integrations/react.stories.mdx
Labels: react, docs

#1298 [EPD-11114] Modus NavBar - User Menu Tooltip
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-navbar/modus-navbar.e2e.ts
  stencil-workspace/src/components/modus-navbar/modus-navbar.models.ts
  stencil-workspace/src/components/modus-navbar/modus-navbar.scss
  stencil-workspace/src/components/modus-navbar/modus-navbar.spec.ts
  stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
  stencil-workspace/src/components/modus-navbar/profile-menu/modus-navbar-profile-menu.tsx
  stencil-workspace/src/components/modus-navbar/readme.md
  stencil-workspace/src/components/modus-tooltip/modus-tooltip.e2e.ts
  stencil-workspace/src/components/modus-tooltip/modus-tooltip.tsx
  stencil-workspace/src/components/modus-tooltip/readme.md
  stencil-workspace/src/interfaces.d.ts
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
  stencil-workspace/storybook/stories/components/modus-tooltip/modus-tooltip-storybook-docs.mdx
Labels: enhancement, e-builder-submission, team-e-builder, breaking-change, team-angry-nerds

#1410 Prevent Azure SWA Deploy Preview being deployed when not needed
  .github/workflows/azure-static-web-apps-deploy.yml
Labels: 1, skip-changelog

#1409 Release v0.1.44-ng14
  angular-workspace/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/projects/trimble-oss/modus-angular-components/package.json
Labels: 1, skip-changelog

#1401 Modus checkbox focus state corrections - focused exclusively on the checkbox and ignoring the label
  stencil-workspace/src/components/modus-checkbox/modus-checkbox.scss
  stencil-workspace/src/components/modus-checkbox/modus-checkbox.spec.tsx
  stencil-workspace/src/components/modus-checkbox/modus-checkbox.tsx
  stencil-workspace/src/components/modus-checkbox/modus-checkbox.vars.scss
  stencil-workspace/src/global/themes.scss
Labels: bug

#1407 Fix Modus Select Accessibility issues and Keyboard Navigation
  stencil-workspace/src/components/modus-select/modus-select.e2e.ts
  stencil-workspace/src/components/modus-select/modus-select.scss
  stencil-workspace/src/components/modus-select/modus-select.spec.ts
  stencil-workspace/src/components/modus-select/modus-select.tsx
  stencil-workspace/src/components/modus-select/modus-select.vars.scss
  stencil-workspace/src/global/modus-variables.scss
  stencil-workspace/src/global/themes.scss
  stencil-workspace/storybook/stories/components/modus-select/modus-select-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-select/modus-select.stories.tsx
Labels: bug, breaking-change

#1423 Update CODEOWNERS
  .github/CODEOWNERS
Labels: 1, skip-changelog

#1424 [EPD-11162] Modus NavBar - Logo Is Responsive
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-navbar/modus-navbar.e2e.ts
  stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
  stencil-workspace/src/components/modus-navbar/readme.md
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
  stencil-workspace/storybook/stories/components/modus-side-navigation/modus-side-navigation-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-side-navigation/modus-side-navigation.stories.tsx
Labels: breaking-change

#1431 Automate external-requests tagging
  .cspell.json
  .github/issue-labeler.yml
  .github/workflows/add-issues-to-modus-project.yml
  .github/workflows/deploy-storybook.yml
  .github/workflows/labeler.yml
  .github/workflows/mend-scan.yml
  .github/workflows/publish-react.yml
  .github/workflows/publish.yml
  .github/workflows/sonar-scan.yml
Labels: 2, github_actions

#1440 Update Modus Tooltip Storybook page to add `disabled` control
  stencil-workspace/storybook/stories/components/modus-tooltip/modus-tooltip.stories.tsx
Labels: 1, bug, docs

#1446 Remove duplicate `ModusNavbarProfileMenuLink` export
  stencil-workspace/src/interfaces.d.ts
Labels: bug

#1448 Release v0.1.45
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#1455 Release v0.1.45-ng14
  angular-workspace/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/projects/trimble-oss/modus-angular-components/package.json
Labels: 1, skip-changelog

#1456 Release v0.1.43-17 (React)
  react-workspace/README.md
  react-workspace/package-lock.json
  react-workspace/package.json
Labels: 1, skip-changelog

#1458 Fix for Trimble logo not showing on Storybook site
  stencil-workspace/storybook/.storybook/manager-head.html
  stencil-workspace/storybook/public/ie11.css
  stencil-workspace/storybook/public/storybook-styles.css
Labels: 1, docs
