Repository trimble-oss/modus-web-components, pull requests merged in 2023-12, with the labels that each got.

#1924 Fixes security vulnerabilitys with @adobe/css-tools
  angular-workspace/ng14/package-lock.json
  angular-workspace/test-web-components/package-lock.json
  angular-workspace/test-web-components/package.json
  react-workspace/test-react-v17/package-lock.json
  react-workspace/test-react-v17/package.json
  react-workspace/test-react-v18/package-lock.json
  react-workspace/test-react-v18/package.json
  react-workspace/test-web-components/package-lock.json
  react-workspace/test-web-components/package.json
  react-workspace/test-web-components/trimble-oss-modus-web-components-0.6.0.tgz
  stencil-workspace/.stylelintrc.json
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
  stencil-workspace/src/components/modus-table/modus-table.tsx
  stencil-workspace/src/components/modus-table/parts/columnHeader/modus-table-column-sort-icon.tsx
Labels: 1, dependencies

#1937 Release Angular & React v0.8.0
  angular-workspace/ng14/angular.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/test-web-components/package-lock.json
  angular-workspace/test-web-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
  react-workspace/test-web-components/package-lock.json
  react-workspace/test-web-components/package.json
Labels: 1, skip-changelog

#1943 Fix false-positives in spellcheck
  .cspell.json
  stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
Labels: 1, skip-changelog

#1951 Release v0.9.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#1952 Release v0.9.0 Angular & React
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/angular.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/angular.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/index.ts
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-17/src/components/stencil-generated/index.ts
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
  react-workspace/react-18/src/components/stencil-generated/index.ts
  stencil-workspace/src/components.d.ts
Labels: 1, skip-changelog

#1932 Fixed exception trying to access oldVal.pageCount in manual pagination
  stencil-workspace/src/components/modus-table/modus-table.e2e.ts
  stencil-workspace/src/components/modus-table/modus-table.tsx
  stencil-workspace/src/components/modus-table/parts/modus-table-pagination.tsx
  stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
Labels: bug

#1962 bug undefined tableCore
  stencil-workspace/src/components/modus-table/modus-table.tsx
Labels: bug

#1961 Fix for font-size for list item
  stencil-workspace/src/components/modus-list-item/modus-list-item.scss
Labels: 1, bug

#1966 Fix checkbox CSS when displayed in tables
  stencil-workspace/src/components/modus-checkbox/modus-checkbox.scss
  stencil-workspace/storybook/stories/components/modus-checkbox/modus-checkbox-storybook-docs.mdx
Labels: bug

#1970 Docs: Remove problematic id="card-title" and id="card-subtitle" from card examples
  angular-workspace/test-ng14/src/examples/modus-card-examples/modus-card-examples.component.ts
  angular-workspace/test-ng15/src/examples/modus-card-examples/modus-card-examples.component.ts
  react-workspace/test-react-v17/src/examples/ModusCardExamples.tsx
  react-workspace/test-react-v18/src/examples/ModusCardExamples.tsx
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/sample.html
  stencil-workspace/storybook/stories/components/modus-card/modus-card-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-card/modus-card.stories.tsx
Labels: 1, bug, docs

#1974 Release v0.10.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: 1, skip-changelog

#1979 Publish v0.10.0 React and Angular
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: 1, skip-changelog
