Repository trimble-oss/modus-web-components, pull requests merged in 2023-05, with the labels that each got.

#1248 Fix syntax highlighting issue
  stencil-workspace/storybook/stories/introduction/getting-started.stories.mdx
Labels: 1, priority:low, docs

#1254 Add VS Code Recommended Extensions and Settings
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
Labels: priority:low, skip-changelog

#1260 Add a reference to Modus Angular Components in Storybook
  angular-workspace/projects/trimble-oss/modus-angular-components/README.md
  stencil-workspace/storybook/stories/framework-integrations/angular.stories.mdx
  stencil-workspace/storybook/stories/introduction/getting-started.stories.mdx
Labels: 1, docs

#1264 (Deprecated Data Table) Fix header min-height
  CONTRIBUTING.md
  stencil-workspace/package.json
  stencil-workspace/src/components/modus-data-table/modus-data-table.scss
Labels: 1, bug

#1266 Fix animation issue in Modus Side navigation component
  stencil-workspace/src/components/modus-side-navigation/modus-side-navigation.scss
  stencil-workspace/src/components/modus-side-navigation/modus-side-navigation.tsx
Labels: bug

#1278 Add google-chat-notifiy GitHub Action
  .github/workflows/google-chat-notifiy.yml
Labels: 1, priority:low, skip-changelog

#1302 Fix for border color on modus-card
  stencil-workspace/src/components/modus-card/modus-card.scss
Labels: 1, bug

#1300 Remove Material Icons from Storybook preview window
  stencil-workspace/storybook/.storybook/preview-head.html
Labels: 1, priority:low, docs

#1296 Add Compact Progress Bar variant (4px height)
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-progress-bar/modus-progress-bar.scss
  stencil-workspace/src/components/modus-progress-bar/modus-progress-bar.spec.ts
  stencil-workspace/src/components/modus-progress-bar/modus-progress-bar.tsx
  stencil-workspace/src/components/modus-progress-bar/readme.md
  stencil-workspace/storybook/stories/components/modus-progress-bar/modus-progress-bar-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-progress-bar/modus-progress-bar.stories.tsx
Labels: 2, enhancement, breaking-change

#1309 Remove mention about needing Material icons on getting-started
  stencil-workspace/storybook/stories/introduction/getting-started.stories.mdx
Labels: 1, docs

#1313 Release v0.1.42
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#1316 Release 0.1.42-ng14
  angular-workspace/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/projects/trimble-oss/modus-angular-components/package.json
Labels: skip-changelog

#1297 Pagination issue fix
  stencil-workspace/src/components/modus-data-table/constants/constants.ts
  stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
Labels: bug

#1322 Fix for Incomplete border line for Modal header and footer
  stencil-workspace/src/components/modus-modal/modus-modal.scss
Labels: bug

#1323 Update pull_request_template
  .github/pull_request_template.md
Labels: 1, priority:low, skip-changelog

#1332 Add `CONSIDERATIONS.md` doc
  CONSIDERATIONS.md
  CONTRIBUTING.md
Labels: skip-changelog

#1315 Added cell value formatter
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-data-table/enums/modus-column-data-type.ts
  stencil-workspace/src/components/modus-data-table/models/modus-data-table-column.ts
  stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
  stencil-workspace/src/components/modus-data-table/parts/modus-data-table-cell-formatter.tsx
  stencil-workspace/src/components/modus-data-table/parts/modus-data-table-cell.tsx
  stencil-workspace/src/components/modus-data-table/parts/modus-data-table-summary-row.tsx
  stencil-workspace/src/components/modus-data-table/readme.md
  stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
Labels: enhancement

#1339 Update Prettier Config ("printWidth": 125)
  .prettierrc.json
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: 2, skip-changelog

#1340 Don't notify google-chat-notify on every comment
  .github/workflows/google-chat-notifiy.yml
Labels: 1, skip-changelog, github_actions

#1329 Added prev Next text option to modus pagination
  stencil-workspace/src/components/modus-pagination/enums/pagination-direction.enum.ts
  stencil-workspace/src/components/modus-pagination/modus-pagination.e2e.ts
  stencil-workspace/src/components/modus-pagination/modus-pagination.scss
  stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
  stencil-workspace/storybook/stories/components/modus-pagination/modus-pagination-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-pagination/modus-pagination.stories.tsx
Labels: enhancement

#1330 Add max-height to Modus-Select
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-content-tree/modus-tree-view/readme.md
  stencil-workspace/src/components/modus-select/modus-select.e2e.ts
  stencil-workspace/src/components/modus-select/modus-select.scss
  stencil-workspace/src/components/modus-select/modus-select.spec.ts
  stencil-workspace/src/components/modus-select/modus-select.tsx
  stencil-workspace/src/components/modus-select/readme.md
  stencil-workspace/storybook/stories/components/modus-select/modus-select-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-select/modus-select.stories.tsx
Labels: bug

#1349 Add Engines to specify minimum version of Node in Package.json
  angular-workspace/package.json
  angular-workspace/projects/trimble-oss/modus-angular-components/package.json
Labels: 1, skip-changelog
