Repository trimble-oss/modus-web-components, pull requests merged in 2023-10, with the labels that each got.

#1752 Release v0.3.1 (React and Angular)
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/test-ng14/angular.json
  angular-workspace/test-ng14/package-lock.json
  angular-workspace/test-ng14/package.json
  angular-workspace/test-ng15/angular.json
  angular-workspace/test-ng15/package-lock.json
  angular-workspace/test-ng15/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
  react-workspace/test-react-v17/package-lock.json
  react-workspace/test-react-v18/package-lock.json
Labels: 1, skip-changelog

#1756 Added references to Modus Styleguide in Contributing guidelines
  .github/ISSUE_TEMPLATE/feature_request.yml
  CONTRIBUTING.md
Labels: skip-changelog

#1759 File Upload Dropzone Accessibility Fixes
  stencil-workspace/src/components/icons/IconMap.tsx
  stencil-workspace/src/components/icons/icon-pencil.tsx
  stencil-workspace/src/components/icons/icon-upload-cloud.tsx
  stencil-workspace/src/components/modus-date-input/modus-date-input.spec.tsx
  stencil-workspace/src/components/modus-date-input/modus-date-input.tsx
  stencil-workspace/src/components/modus-file-dropzone/modus-file-dropzone.scss
  stencil-workspace/src/components/modus-file-dropzone/modus-file-dropzone.spec.ts
  stencil-workspace/src/components/modus-file-dropzone/modus-file-dropzone.tsx
  stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
Labels: 1, accessibility

#1769 Typo fixes
  .cspell.json
  angular-workspace/test-ng14/src/examples/modus-file-dropzone-examples/modus-file-dropzone-examples.component.ts
  angular-workspace/test-ng15/src/examples/modus-file-dropzone-examples/modus-file-dropzone-examples.component.ts
Labels: 1, bug, skip-changelog

#1768 EPD-11706 Issue 1758/date input with a space is still showing an error
  stencil-workspace/src/components/modus-date-input/modus-date-input.e2e.ts
  stencil-workspace/src/components/modus-date-input/modus-date-input.tsx
Labels: bug

#1778 Release v0.4.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
  stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-editor/modus-table-cell-editor.tsx
  stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
Labels: 1, skip-changelog

#1779 Fix for modus-date-picker failing test
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
  stencil-workspace/src/components/modus-date-input/modus-date-input.tsx
  stencil-workspace/src/components/modus-date-input/utils/modus-date-input.formatter.tsx
  stencil-workspace/src/components/modus-date-picker/modus-date-picker.e2e.ts
  stencil-workspace/src/components/modus-date-picker/modus-date-picker.tsx
Labels: 1, bug

#1780 Release v0141 - React and Angular
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: 1, skip-changelog

#1781 Add 'thanks for the issue' Automated comment for new issues
  .github/workflows/issue-thanks.yml
  CONTRIBUTING.md
  stencil-workspace/.nvmrc
Labels: 1, skip-changelog

#1790 Update issue-thanks.yml
  .github/workflows/issue-thanks.yml
Labels: 1, skip-changelog

#1812 Fix the non-accessible hyperlink cell content in Modus Table
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-alert/modus-alert.scss
  stencil-workspace/src/components/modus-table/modus-table.e2e.ts
  stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-link-element.tsx
  stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-main/modus-table-cell-main.tsx
  stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-main/readme.md
  stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell.tsx
  stencil-workspace/src/components/modus-table/parts/modus-table-body.tsx
  stencil-workspace/src/components/modus-table/parts/row/selection/modus-table-cell-checkbox.tsx
  stencil-workspace/src/components/modus-table/utilities/table-cell-navigation.utility.tsx
  stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
  stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
Labels: bug

#1816 Release v050
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#1817 Release v050 - React & Angular
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: skip-changelog

#1835 Fix dev dep issues and fix some build errors
  .cspell.json
  .gitignore
  angular-workspace/ng14/angular.json
  angular-workspace/ng14/package-lock.json
  angular-workspace/ng15/package-lock.json
  angular-workspace/test-ng14/package-lock.json
  angular-workspace/test-ng14/package.json
  angular-workspace/test-ng15/angular.json
  angular-workspace/test-ng15/package-lock.json
  angular-workspace/test-ng15/package.json
  package.json
  react-workspace/test-react-v17/package-lock.json
  react-workspace/test-react-v17/package.json
  react-workspace/test-react-v17/src/examples/ModusTableExamples.tsx
  react-workspace/test-react-v18/package-lock.json
  react-workspace/test-react-v18/package.json
  react-workspace/test-react-v18/src/App.css
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-table/models/modus-table.models.ts
  stencil-workspace/src/components/modus-table/models/row-actions.model.ts
  stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-main/modus-table-cell-main.tsx
  stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-main/readme.md
  stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell.tsx
  stencil-workspace/src/components/modus-table/parts/modus-table-body.tsx
Labels: 2, dependencies, devOps, security-issue

#1836 Release v0.15.1
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
  stencil-workspace/storybook/package-lock.json
  stencil-workspace/storybook/package.json
Labels: 1, skip-changelog

#1837 Release v0151 for React and Angular
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
  react-workspace/test-web-components/package-lock.json
  react-workspace/test-web-components/package.json
Labels: skip-changelog
