Repository trimble-oss/modus-web-components, pull requests merged in 2023-11, with the labels that each got.

#1852 Modus Chip - Added `max-width` to handle text overflow
  stencil-workspace/src/components/modus-chip/modus-chip.e2e.ts
  stencil-workspace/src/components/modus-chip/modus-chip.scss
  stencil-workspace/src/components/modus-chip/modus-chip.tsx
  stencil-workspace/src/components/modus-chip/readme.md
  stencil-workspace/storybook/stories/components/modus-chip/modus-chip-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-chip/modus-chip.stories.tsx
Labels: bug

#1866 Rename class name for sun icon
  stencil-workspace/src/components/icons/icon-sun.tsx
Labels: bug

#1874 Fix for Failed Avatar navbar example is not using a valid URL
  angular-workspace/test-ng14/src/examples/modus-navbar-examples/modus-navbar-examples.component.ts
  angular-workspace/test-ng15/src/examples/modus-navbar-examples/modus-navbar-examples.component.ts
  stencil-workspace/src/components/modus-navbar/modus-navbar.scss
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
  stencil-workspace/storybook/stories/components/modus-side-navigation/modus-side-navigation-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-side-navigation/modus-side-navigation.stories.tsx
Labels: bug

#1882 Docs: Set color-scheme: dark when in dark mode.
  .cspell.json
  .github/workflows/labeler.yml
  stencil-workspace/storybook/public/storybook-styles.css
Labels: docs

#1885 Release v0.6.0 React & Angular
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: 1, skip-changelog

#1886 Release v060 React
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: skip-changelog

#1893 Issue 1572 Modus-Table: Fix when reordering the columns, the cell text is getting highlighted
  stencil-workspace/src/components/modus-table/modus-table.scss
  stencil-workspace/src/components/modus-table/parts/columnHeader/modus-table-column-header.tsx
Labels: bug

#1902 Release v0.7.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#1903 Release v070 - React & Angular
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: skip-changelog
