Repository trimble-oss/modus-web-components, pull requests merged in 2023-09, with the labels that each got.

#1682 Fix for starting date within the week in the month view
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
  stencil-workspace/src/components/modus-date-picker/modus-date-picker.scss
  stencil-workspace/src/components/modus-date-picker/modus-date-picker.tsx
  stencil-workspace/src/components/modus-date-picker/utils/modus-date-picker.calendar.tsx
Labels: bug

#1670 Fix the default padding for dropdown menus in Modus Navbar component
  stencil-workspace/src/components/modus-navbar/apps-menu/modus-navbar-apps-menu.scss
  stencil-workspace/src/components/modus-navbar/modus-navbar.vars.scss
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
Labels: bug, breaking-change

#1692 Bump version to v0.1.53
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: 1, skip-changelog

#1705 Update version for Angular and React packages (v0.1.55)
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: 1, skip-changelog

#1716 Release v0.2.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: 1, skip-changelog

#1717 Bump version for React and Angular v0.2.0
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: 1, skip-changelog

#1726 Update Notifications Bell Icon
  stencil-workspace/src/components/icons/icon-notifications.tsx
Labels: 1, bug

#1727 Fix azure-static-web-apps-deploy issue
  .github/workflows/azure-static-web-apps-deploy.yml
Labels: 1, bug, skip-changelog

#1732 Release v0.3.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
  stencil-workspace/storybook/stories/components/modus-button/modus-button-storybook-docs.mdx
Labels: 1, skip-changelog

#1733 Bump version for React and Angular release
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/test-ng14/package-lock.json
  angular-workspace/test-ng15/package-lock.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
  react-workspace/test-react-v17/package-lock.json
  react-workspace/test-react-v18/package-lock.json
Labels: 1, skip-changelog
