Repository trimble-oss/modus-web-components, pull requests merged in 2023-07, with the labels that each got.

#1497 Add missing watch for Modus Text Input `value` prop
  stencil-workspace/src/components/modus-text-input/modus-text-input.e2e.ts
  stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
Labels: bug

#1284 [EPD-11101] Search - add overlay and search functionality to Modus bar
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/index.ts
  react-workspace/react-17/src/components/stencil-generated/index.ts
  react-workspace/react-18/src/components/stencil-generated/index.ts
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/icons/icon-close.tsx
  stencil-workspace/src/components/icons/icon-search.tsx
  stencil-workspace/src/components/modus-navbar/modus-navbar.e2e.ts
  stencil-workspace/src/components/modus-navbar/modus-navbar.scss
  stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
  stencil-workspace/src/components/modus-navbar/readme.md
  stencil-workspace/src/components/modus-navbar/search-overlay/modus-navbar-search-overlay.scss
  stencil-workspace/src/components/modus-navbar/search-overlay/modus-navbar-search-overlay.tsx
  stencil-workspace/src/components/modus-navbar/search-overlay/readme.md
  stencil-workspace/src/components/modus-text-input/modus-text-input.scss
  stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
  stencil-workspace/src/components/modus-text-input/readme.md
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
Labels: enhancement, e-builder-submission, team-e-builder, team-angry-nerds

#1491 Added support for slot in Modus Alert
  stencil-workspace/src/components/modus-alert/modus-alert.e2e.ts
  stencil-workspace/src/components/modus-alert/modus-alert.scss
  stencil-workspace/src/components/modus-alert/modus-alert.spec.ts
  stencil-workspace/src/components/modus-alert/modus-alert.tsx
  stencil-workspace/src/components/modus-alert/modus-alert.vars.scss
  stencil-workspace/src/global/themes.scss
  stencil-workspace/storybook/public/storybook-styles.css
  stencil-workspace/storybook/stories/components/modus-alert/modus-alert-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-alert/modus-alert.stories.tsx
  stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx
Labels: 2, enhancement

#1514 Update the open github issues link in Modus Data Table deprecation warning message
  stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx
Labels: 1

#1552 Remove duplicate interfaces export and make tooltip nullable for Modus Navbar `buttons` property
  react-workspace/react-17/src/components/stencil-generated/react-component-lib/utils/attachProps.ts
  react-workspace/react-18/src/components/stencil-generated/react-component-lib/utils/attachProps.ts
  stencil-workspace/src/components/modus-navbar/modus-navbar.models.ts
  stencil-workspace/src/interfaces.d.ts
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
Labels: bug, angular

#1553 Release v0147
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: 1, skip-changelog

#1556 Bump version numbers for Angular and React packages to v0.1.47
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: 1, skip-changelog

#1559 Fix GitHub Labeler Action
  .github/workflows/labeler.yml
Labels: 1, priority:low

#1560 Automate publishing Angular MWC packages to npm and GitHub reg
  .github/workflows/publish-angular.yml
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/README.md
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/README.md
Labels: 3

#1544 Modus Table - Add support for Expandable rows
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/icons/icon-chevron-up-thick.tsx
  stencil-workspace/src/components/modus-table/models/modus-table-column.ts
  stencil-workspace/src/components/modus-table/modus-table.e2e.ts
  stencil-workspace/src/components/modus-table/modus-table.scss
  stencil-workspace/src/components/modus-table/modus-table.tsx
  stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-formatter.tsx
  stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell.tsx
  stencil-workspace/src/components/modus-table/parts/header/modus-table-header.tsx
  stencil-workspace/src/components/modus-table/parts/modus-table-cell.tsx
  stencil-workspace/src/components/modus-table/parts/modus-table-pagination.tsx
  stencil-workspace/src/components/modus-table/readme.md
  stencil-workspace/src/components/modus-table/utilities/table-header-drag-drop.utility.tsx
  stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
Labels: table

#1563 Add update script to root
  package-lock.json
  package.json
Labels: 3

#1545 Modal component - Added `backdrop='static'` option to allow clicking outside the Modal content
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-modal/modus-modal.e2e.ts
  stencil-workspace/src/components/modus-modal/modus-modal.tsx
  stencil-workspace/src/components/modus-modal/readme.md
  stencil-workspace/storybook/stories/components/modus-modal/modus-modal-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-modal/modus-modal.stories.tsx
Labels: enhancement

#1565 Release v0148
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: 1, skip-changelog

#1568 Add a Storybook page for contributing guidelines
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/angular-component-lib/utils.ts
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/boolean-value-accessor.ts
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/index.ts
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/select-value-accessor.ts
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/text-value-accessor.ts
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/value-accessor.ts
  stencil-workspace/storybook/.storybook/preview.js
  stencil-workspace/storybook/stories/introduction/contributing.stories.mdx
Labels: docs

#1538 Modus Table scrollbar development
  stencil-workspace/src/components/modus-table/modus-table.scss
  stencil-workspace/src/components/modus-table/modus-table.spec.tsx
  stencil-workspace/src/components/modus-table/modus-table.tsx
  stencil-workspace/src/components/modus-table/modus-table.vars.scss
  stencil-workspace/src/components/modus-table/parts/modus-table-summary-row.tsx
  stencil-workspace/src/global/themes.scss
  stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
Labels: table

#1586 Fix for npm publish steps GH Action
  .github/workflows/publish-angular.yml
  package.json
Labels: devOps, skip-changelog
