Repository trimble-oss/modus-web-components, pull requests merged in 2024-11, with the labels that each got.

#2942 Remove `aria-checked` (not needed)
  stencil-workspace/src/components/modus-checkbox/modus-checkbox.spec.tsx
  stencil-workspace/src/components/modus-checkbox/modus-checkbox.tsx
  stencil-workspace/storybook/stories/components/modus-checkbox/modus-checkbox-storybook-docs.mdx
Labels: accessibility

#2935 Accordion: Add supporting label and fix left icon spacing
  stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.e2e.ts
  stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.scss
  stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.spec.ts
  stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.tsx
  stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.vars.scss
  stencil-workspace/src/components/modus-accordion-item/readme.md
  stencil-workspace/src/global/themes.scss
  stencil-workspace/storybook/stories/components/modus-accordion/modus-accordion-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-accordion/modus-accordion.stories.tsx
Labels: modus-accordion

#2938 DatePicker: bug with errorText
  stencil-workspace/src/components/modus-date-input/modus-date-input.e2e.ts
  stencil-workspace/src/components/modus-date-input/modus-date-input.tsx
Labels: bug, modus-date-picker

#2959 Release v0141 - React & Angular
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package.json
  package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: skip-changelog

#2966 Table: Add null check to table pagination's optionsDisplayProp
  stencil-workspace/src/components/modus-table/parts/modus-table-pagination.tsx
Labels: bug

#2964 Alerts: Fix Warning / Error BG color CSS
  stencil-workspace/src/components/modus-alert/modus-alert.vars.scss
Labels: bug

#2962 Table : Fix cancel icon in row action column
  stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
Labels: bug

#2954 Table: expandable rows not working in single row table
  stencil-workspace/src/components/modus-table/modus-table.core.tsx
  stencil-workspace/src/components/modus-table/modus-table.tsx
Labels: bug

#2967 Release v0-41-1
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#2968 Release v0.14.1 - Angular & React
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: skip-changelog

#2969 Dependency Updates
  angular-workspace/ng14/package-lock.json
  angular-workspace/ng14/package.json
  angular-workspace/ng15/package-lock.json
  angular-workspace/ng15/package.json
  angular-workspace/ng16/package-lock.json
  angular-workspace/ng16/package.json
  angular-workspace/ng17/package-lock.json
  angular-workspace/ng17/package.json
  angular-workspace/ng18/package-lock.json
  angular-workspace/ng18/package.json
  angular-workspace/test-ng14/package-lock.json
  angular-workspace/test-ng14/package.json
  angular-workspace/test-ng15/package-lock.json
  angular-workspace/test-ng15/package.json
  angular-workspace/test-web-components/package.json
  react-workspace/test-react-v17/package.json
  react-workspace/test-react-v18/package-lock.json
  react-workspace/test-react-v18/package.json
  react-workspace/test-web-components/package-lock.json
  react-workspace/test-web-components/package.json
Labels: dependencies, skip-changelog

#2972 npm registry fix
  .npmrc
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package-lock.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-18/package-lock.json
Labels: bug, skip-changelog

#2963 Autocomplete controls the behavior of read only functionality is not as expected
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.e2e.ts
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.scss
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.vars.scss
  stencil-workspace/src/global/themes.scss
Labels: bug, modus-autocomplete

#2976 Radio group: keyboard navigation for next and previous option
  stencil-workspace/src/components/modus-radio-group/modus-radio-button.tsx
  stencil-workspace/src/components/modus-radio-group/modus-radio-group.e2e.ts
  stencil-workspace/src/components/modus-radio-group/modus-radio-group.tsx
  stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group.stories.tsx
Labels: bug

#2973 Content Tree: Fix text being selected when expanding a section
  stencil-workspace/src/components/modus-content-tree/modus-tree-view-item/modus-tree-view-item.scss
Labels: bug

#3020 Bump cross-spawn from 15.11.0 to 16.10.0 in /stencil-workspace
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
  stencil-workspace/src/components/modus-tabs/modus-tabs.scss
Labels: dependencies

#3008 Checkbox: Fix Space bar Functionality for Toggle Behavior
  stencil-workspace/src/components/modus-checkbox/modus-checkbox.e2e.ts
  stencil-workspace/src/components/modus-checkbox/modus-checkbox.tsx
Labels: bug

#2998 Table: Allow translated strings for pagination and sorting
  stencil-workspace/src/components/modus-table/modus-table.e2e.ts
  stencil-workspace/src/components/modus-table/parts/columnHeader/modus-table-column-header-label.tsx
  stencil-workspace/src/components/modus-table/parts/modus-table-pagination.tsx
  stencil-workspace/src/lang/translations.ts
Labels: modus-table

#2977 Modal: Close button displays top left if headerText is not provided
  stencil-workspace/src/components/modus-modal/modus-modal.scss
Labels: bug, modus-modal

#3024 Update Storybook Dev Dependencies
  stencil-workspace/package.json
  stencil-workspace/storybook/.npmrc
  stencil-workspace/storybook/package-lock.json
  stencil-workspace/storybook/package.json
Labels: dependencies, skip-changelog

#3025 Minor docs fixes
  .cspell.json
  .github/copilot-instructions.md
  .github/workflows/add-issues-to-modus-project.yml
  package.json
  stencil-workspace/storybook/.storybook/manager-head.html
  stencil-workspace/storybook/public/404/index.html
  stencil-workspace/storybook/public/storybook-styles.css
Labels: bug, docs

#2871 Button: add critical action feature
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-button/modus-button.e2e.ts
  stencil-workspace/src/components/modus-button/modus-button.scss
  stencil-workspace/src/components/modus-button/modus-button.tsx
  stencil-workspace/src/components/modus-button/modus-button.vars.scss
  stencil-workspace/src/components/modus-button/readme.md
  stencil-workspace/storybook/stories/components/modus-button/modus-button-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-button/modus-button.stories.tsx
Labels: modus-button

#2887 Table: Row Action Column Accessibility issues
  stencil-workspace/src/components/modus-table/models/modus-table.models.ts
  stencil-workspace/src/components/modus-table/models/table-context.models.ts
  stencil-workspace/src/components/modus-table/modus-table.tsx
  stencil-workspace/src/components/modus-table/parts/modus-table-header.tsx
  stencil-workspace/src/components/modus-table/parts/row/selection/modus-table-header-checkbox.tsx
  stencil-workspace/src/components/modus-table/readme.md
  stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
Labels: accessibility, docs

#3033 Docs: Storybook Link Fixes
  .htmlhintrc
  stencil-workspace/src/components.d.ts
  stencil-workspace/storybook/public/storybook-styles.css
  stencil-workspace/storybook/stories/components/modus-accordion/modus-accordion-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-alert/modus-alert-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-badge/modus-badge-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-breadcrumb/modus-breadcrumb-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-button-group/modus-button-group-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-button/modus-button-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-card/modus-card-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-chip/modus-chip-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-message/modus-message-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-pagination/modus-pagination-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-progress-bar/modus-progress-bar-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-slider/modus-slider-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-switch/modus-switch-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-toast/modus-toast-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-tooltip/modus-tooltip-storybook-docs.mdx
Labels: docs

#2999 Modus Text Input: name prop added and enabled the formAssociated for form validation
  stencil-workspace/src/components/modus-text-input/modus-text-input.e2e.ts
  stencil-workspace/src/components/modus-text-input/modus-text-input.spec.tsx
  stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
  stencil-workspace/src/components/modus-text-input/readme.md
  stencil-workspace/storybook/stories/components/modus-content-tree/modus-content-tree.stories.tsx
  stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input.stories.tsx
Labels: modus-text-input

#3042 GitHub Actions: Update to use Node v18
  .github/workflows/publish-angular.yml
  .github/workflows/publish-react.yml
  react-workspace/react-17/.npmrc
  react-workspace/react-18/.npmrc
Labels: github_actions
