Repository trimble-oss/modus-web-components, pull requests merged in 2024-02, with the labels that each got.

#2104 Fix storybook issue with icon names being cropped
  stencil-workspace/storybook/stories/components/modus-icons/modus-icons.stories.tsx
Labels: 1, docs

#2107 Form inputs: CSS change to `border-radius: 4px`
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.scss
  stencil-workspace/src/components/modus-date-input/modus-date-input.scss
  stencil-workspace/src/components/modus-date-picker/modus-date-picker.scss
  stencil-workspace/src/components/modus-number-input/modus-number-input.scss
  stencil-workspace/src/components/modus-select/modus-select.scss
  stencil-workspace/src/components/modus-text-input/modus-text-input.scss
  stencil-workspace/src/components/modus-time-picker/modus-time-picker.scss
Labels: 3

#2112 Release v0.15.0 - (React & Angular)
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: skip-changelog

#2087 Autocomplete: Allow user to scroll through items in the dropdown
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.e2e.ts
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
Labels: accessibility, team-e-builder

#2106 Table: Bold table header text on sort
  stencil-workspace/src/components/modus-table/modus-table.e2e.ts
  stencil-workspace/src/components/modus-table/modus-table.scss
  stencil-workspace/src/components/modus-table/parts/columnHeader/modus-table-column-header.tsx
Labels: team-e-builder

#2118 Tabs: Fixed the missed ids and wrong tabIndex issues
  stencil-workspace/src/components/modus-tabs/modus-tabs.e2e.ts
  stencil-workspace/src/components/modus-tabs/modus-tabs.spec.ts
  stencil-workspace/src/components/modus-tabs/modus-tabs.tsx
Labels: bug, accessibility

#2120 Alert: Icon shrinking issue
  stencil-workspace/src/components/modus-alert/modus-alert.scss
  stencil-workspace/src/components/modus-alert/modus-alert.spec.ts
  stencil-workspace/src/components/modus-alert/modus-alert.tsx
Labels: bug

#2119 Accordion: Accessibility issues
  stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.spec.ts
  stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.tsx
Labels: bug, accessibility

#2036 Navbar: Add Active/Pressed State to buttons
  stencil-workspace/src/components/modus-icons/readme.md
  stencil-workspace/src/icons/svgs/icon-apps.tsx
  stencil-workspace/src/icons/svgs/icon-arrow-down.tsx
  stencil-workspace/src/icons/svgs/icon-arrow-up.tsx
  stencil-workspace/src/icons/svgs/icon-calendar.tsx
  stencil-workspace/src/icons/svgs/icon-cancel.tsx
  stencil-workspace/src/icons/svgs/icon-caret-down.tsx
  stencil-workspace/src/icons/svgs/icon-caret-up.tsx
  stencil-workspace/src/icons/svgs/icon-check-circle.tsx
  stencil-workspace/src/icons/svgs/icon-check.tsx
  stencil-workspace/src/icons/svgs/icon-chevron-double-down.tsx
  stencil-workspace/src/icons/svgs/icon-chevron-double-up.tsx
  stencil-workspace/src/icons/svgs/icon-chevron-down-thick.tsx
  stencil-workspace/src/icons/svgs/icon-chevron-left-thick.tsx
  stencil-workspace/src/icons/svgs/icon-chevron-right-thick.tsx
  stencil-workspace/src/icons/svgs/icon-chevron-up-thick.tsx
  stencil-workspace/src/icons/svgs/icon-close.tsx
  stencil-workspace/src/icons/svgs/icon-delete.tsx
  stencil-workspace/src/icons/svgs/icon-download-line.tsx
  stencil-workspace/src/icons/svgs/icon-error.tsx
  stencil-workspace/src/icons/svgs/icon-export.tsx
  stencil-workspace/src/icons/svgs/icon-help.tsx
  stencil-workspace/src/icons/svgs/icon-history.tsx
  stencil-workspace/src/icons/svgs/icon-horizontal-ellipsis.tsx
  stencil-workspace/src/icons/svgs/icon-indeterminate.tsx
  stencil-workspace/src/icons/svgs/icon-info.tsx
  stencil-workspace/src/icons/svgs/icon-menu.tsx
  stencil-workspace/src/icons/svgs/icon-moon.tsx
  stencil-workspace/src/icons/svgs/icon-notifications.tsx
  stencil-workspace/src/icons/svgs/icon-pencil.tsx
  stencil-workspace/src/icons/svgs/icon-refresh.tsx
  stencil-workspace/src/icons/svgs/icon-remove.tsx
  stencil-workspace/src/icons/svgs/icon-search.tsx
  stencil-workspace/src/icons/svgs/icon-smiley-dissatisfied-outline.tsx
  stencil-workspace/src/icons/svgs/icon-smiley-dissatisfied.tsx
  stencil-workspace/src/icons/svgs/icon-smiley-neutral-outline.tsx
  stencil-workspace/src/icons/svgs/icon-smiley-neutral.tsx
  stencil-workspace/src/icons/svgs/icon-smiley-satisfied-outline.tsx
  stencil-workspace/src/icons/svgs/icon-smiley-satisfied.tsx
  stencil-workspace/src/icons/svgs/icon-smiley-somewhat-dissatisfied-outline.tsx
  stencil-workspace/src/icons/svgs/icon-smiley-somewhat-dissatisfied.tsx
  stencil-workspace/src/icons/svgs/icon-smiley-somewhat-satisfied-outline.tsx
  stencil-workspace/src/icons/svgs/icon-smiley-somewhat-satisfied.tsx
  stencil-workspace/src/icons/svgs/icon-sort-a-z.tsx
  stencil-workspace/src/icons/svgs/icon-sort-z-a.tsx
  stencil-workspace/src/icons/svgs/icon-sun.tsx
  stencil-workspace/src/icons/svgs/icon-thumbs-down-outlined.tsx
  stencil-workspace/src/icons/svgs/icon-thumbs-down.tsx
  stencil-workspace/src/icons/svgs/icon-thumbs-up-outline.tsx
  stencil-workspace/src/icons/svgs/icon-thumbs-up.tsx
  stencil-workspace/src/icons/svgs/icon-triangle-down.tsx
  stencil-workspace/src/icons/svgs/icon-triangle-left.tsx
  stencil-workspace/src/icons/svgs/icon-tune.tsx
  stencil-workspace/src/icons/svgs/icon-upload-cloud.tsx
  stencil-workspace/src/icons/svgs/icon-visibility-off.tsx
  stencil-workspace/src/icons/svgs/icon-visibility.tsx
  stencil-workspace/src/icons/svgs/icon-warning.tsx
Labels: e-builder-submission, team-e-builder

#2130 Release v0.16.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: 1, skip-changelog

#2146 Table: Fix Row Action More Icon
  stencil-workspace/src/components/modus-table/parts/row/actions/modus-table-row-actions/modus-table-row-actions.tsx
Labels: bug

#2123 Table: column resize accessibility issues
  stencil-workspace/src/components/modus-table/modus-table.scss
  stencil-workspace/src/components/modus-table/parts/columnHeader/modus-table-column-resizing-handler.tsx
  stencil-workspace/src/components/modus-table/parts/fillerColumn/modus-table-filler-column.tsx
Labels: team-e-builder

#2150 Navbar: Use `type="search"` on search input
  stencil-workspace/src/components/modus-navbar/search-overlay/modus-navbar-search-overlay.tsx
Labels: accessibility

#2096 Content Tree: Adding action button for modus content tree
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/index.ts
  react-workspace/react-17/src/components/stencil-generated/index.ts
  react-workspace/react-18/src/components/stencil-generated/index.ts
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-action-bar/modus-action-bar.scss
  stencil-workspace/src/components/modus-action-bar/modus-action-bar.tsx
  stencil-workspace/src/components/modus-action-bar/readme.md
  stencil-workspace/src/components/modus-button/readme.md
  stencil-workspace/src/components/modus-content-tree/modus-content-tree.e2e.ts
  stencil-workspace/src/components/modus-content-tree/modus-content-tree.spec.tsx
  stencil-workspace/src/components/modus-content-tree/modus-tree-view-item/modus-tree-view-item.scss
  stencil-workspace/src/components/modus-content-tree/modus-tree-view-item/modus-tree-view-item.tsx
  stencil-workspace/src/components/modus-content-tree/modus-tree-view-item/readme.md
  stencil-workspace/src/components/modus-content-tree/modus-tree-view/modus-tree-view.tsx
  stencil-workspace/src/components/modus-content-tree/modus-tree-view/readme.md
  stencil-workspace/src/components/modus-icons/readme.md
  stencil-workspace/src/components/modus-list-item/modus-list-item.tsx
  stencil-workspace/src/components/modus-list-item/readme.md
  stencil-workspace/src/components/modus-list/readme.md
  stencil-workspace/src/components/modus-tooltip/readme.md
  stencil-workspace/storybook/stories/components/modus-content-tree/modus-content-tree-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-content-tree/modus-content-tree.stories.tsx
Labels: team-e-builder

#2153 Release v0.17.0
  .prettierignore
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#2154 Release v0.17.0 - React & Angular
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: 1, skip-changelog

#2121 Sentiment Scale: Accessibility issues
  stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.e2e.ts
  stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.spec.ts
  stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
  stencil-workspace/storybook/stories/components/modus-sentiment-scale/modus-sentiment-scale.stories.tsx
Labels: accessibility

#2156 Sentiment Scale: Minor code cleanup
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
  stencil-workspace/src/components/modus-sentiment-scale/readme.md
  stencil-workspace/storybook/stories/components/modus-sentiment-scale/modus-sentiment-scale-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-sentiment-scale/modus-sentiment-scale.stories.tsx
Labels: accessibility, docs

#2160 Update Modus Icons to v1.10.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
  stencil-workspace/src/components/modus-icons/readme.md
Labels: dependencies

#2163 Docs: Content Tree Custom Filter Example allow `Esc` to clear input
  stencil-workspace/storybook/stories/components/modus-content-tree/modus-content-tree.stories.tsx
Labels: docs

#2166 Breadcrumb: Remove unnecessary `role="navigation"` from navs
  stencil-workspace/src/components/modus-breadcrumb/modus-breadcrumb.spec.ts
  stencil-workspace/src/components/modus-breadcrumb/modus-breadcrumb.tsx
  stencil-workspace/src/components/modus-side-navigation/modus-side-navigation.spec.tsx
  stencil-workspace/src/components/modus-side-navigation/modus-side-navigation.tsx
Labels: 1, accessibility

#2171 Docs: fix Canvas demos accessibility issue
  stencil-workspace/storybook/stories/components/modus-autocomplete/modus-autocomplete.stories.tsx
  stencil-workspace/storybook/stories/components/modus-button/modus-button.stories.tsx
  stencil-workspace/storybook/stories/components/modus-checkbox/modus-checkbox.stories.tsx
  stencil-workspace/storybook/stories/components/modus-chip/modus-chip.stories.tsx
  stencil-workspace/storybook/stories/components/modus-date-picker/modus-date-picker.stories.tsx
  stencil-workspace/storybook/stories/components/modus-number-input/modus-number-input.stories.tsx
  stencil-workspace/storybook/stories/components/modus-slider/modus-slider.stories.tsx
  stencil-workspace/storybook/stories/components/modus-switch/modus-switch.stories.tsx
  stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input.stories.tsx
  stencil-workspace/storybook/stories/components/modus-time-picker/modus-time-picker.stories.tsx
  stencil-workspace/storybook/stories/components/modus-tooltip/modus-tooltip.stories.tsx
Labels: accessibility, docs

#2172 Docs: Use `<kbd>` for keyboard inputs
  .cspell.json
  stencil-workspace/storybook/public/storybook-styles.css
  stencil-workspace/storybook/stories/components/modus-accordion/modus-accordion-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-alert/modus-alert-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-breadcrumb/modus-breadcrumb-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-button/modus-button-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-checkbox/modus-checkbox-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-chip/modus-chip-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-content-tree/modus-content-tree-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-date-picker/modus-date-picker-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-file-dropzone/modus-file-dropzone-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-modal/modus-modal-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-pagination/modus-pagination-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-select/modus-select-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-sentiment-scale/modus-sentiment-scale-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-side-navigation/modus-side-navigation-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-switch/modus-switch-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-tabs/modus-tabs-storybook-docs.mdx
Labels: docs

#2174 Button: Remove `role=button`
  stencil-workspace/src/components/modus-button/modus-button.spec.ts
  stencil-workspace/src/components/modus-button/modus-button.tsx
Labels: 1, accessibility

#2175 Input: Text & Number Accessibility issue
  stencil-workspace/src/components/modus-number-input/modus-number-input.spec.tsx
  stencil-workspace/src/components/modus-number-input/modus-number-input.tsx
  stencil-workspace/src/components/modus-text-input/modus-text-input.spec.tsx
  stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
Labels: accessibility

#2191 Release v0.18.0 - Update React Angular
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: skip-changelog

#2202 Docs: Fix Alert Doc Inconsistency
  stencil-workspace/storybook/stories/components/modus-alert/modus-alert-storybook-docs.mdx
Labels: docs

#2196 Breadcrumbs: Add underline property
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-breadcrumb/modus-breadcrumb.scss
  stencil-workspace/src/components/modus-breadcrumb/modus-breadcrumb.tsx
  stencil-workspace/src/components/modus-breadcrumb/readme.md
  stencil-workspace/storybook/stories/components/modus-breadcrumb/modus-breadcrumb-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-breadcrumb/modus-breadcrumb.stories.tsx
Labels: accessibility

#2207 Navbar: Use correct logoOptions prop in Navbar storybook
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
Labels: docs

#2209 Navbar: Apps Menu Image Accessibility & CSS fix
  stencil-workspace/src/components/modus-navbar/apps-menu/modus-navbar-apps-menu.scss
  stencil-workspace/src/components/modus-navbar/apps-menu/modus-navbar-apps-menu.tsx
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
Labels: accessibility

#2139 Navbar: Toggle dropdown menus of navbar with Enter,Space and close with Escape
  stencil-workspace/src/components/modus-dropdown/modus-dropdown.spec.ts
  stencil-workspace/src/components/modus-dropdown/modus-dropdown.tsx
  stencil-workspace/src/components/modus-navbar/button-list/modus-navbar-button-list.tsx
  stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
Labels: accessibility

#2220 Text Input: password visibility icon fix
  stencil-workspace/src/components/modus-text-input/modus-text-input.scss
  stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
Labels: bug

#2221 Pagination & Side Nav: Update to use correct chevron icons.
  stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
  stencil-workspace/src/components/modus-side-navigation/modus-side-navigation-item/modus-side-navigation-item.scss
  stencil-workspace/src/components/modus-side-navigation/modus-side-navigation-item/modus-side-navigation-item.tsx
  stencil-workspace/src/components/modus-side-navigation/modus-side-navigation.scss
  stencil-workspace/src/components/modus-side-navigation/modus-side-navigation.tsx
  stencil-workspace/storybook/stories/components/modus-side-navigation/modus-side-navigation-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-side-navigation/modus-side-navigation.stories.tsx
Labels: bug

#2224 Release v0.19.0 - Update React and Angular
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: skip-changelog
