Repository trimble-oss/modus-web-components, pull requests merged in 2024-04, with the labels that each got.

#2389 Radio group: Update documentation
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-radio-group/modus-radio-group.tsx
  stencil-workspace/src/components/modus-radio-group/readme.md
  stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group-storybook-docs.mdx
Labels: docs

#2351 Input: Add `autocapitalize`, `autocorrect`, `enterkeyhint`, and `spellcheck `properties
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-text-input/modus-text-input.spec.tsx
  stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
  stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input.stories.tsx
Labels: text-input

#2390 Docs: Add `pattern` attribute to text-input page
  stencil-workspace/src/index.html
  stencil-workspace/src/sample.html
  stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input-storybook-docs.mdx
Labels: 1, docs

#2378 Sentiment Scale: Remove `aria-disabled` attribute when not disabled
  stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.e2e.ts
  stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.spec.ts
  stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
Labels: accessibility

#2338 Table: Fix linting warning resulting from using `any` type
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-icons/readme.md
  stencil-workspace/src/components/modus-table/parts/row/actions/modus-table-row-actions/modus-table-row-actions.tsx
  stencil-workspace/src/components/modus-table/parts/row/actions/modus-table-row-actions/readme.md
Labels: bug, table

#2124 Table: Footer honors density property
  stencil-workspace/src/components/modus-table/modus-table.scss
  stencil-workspace/src/components/modus-table/parts/fillerColumn/modus-table-filler-column.scss
Labels: table

#2375 Bump @trimble-oss/modus-icons from 1.11.0 to 1.12.0 in /stencil-workspace
  .github/dependabot.yml
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
  stencil-workspace/src/components/modus-icons/readme.md
Labels: dependencies

#2396 Dropdown: Fix issue where enter, escape, and space key are not having desired output
  stencil-workspace/src/components/modus-dropdown/modus-dropdown.e2e.ts
  stencil-workspace/src/components/modus-dropdown/modus-dropdown.spec.ts
  stencil-workspace/src/components/modus-dropdown/modus-dropdown.tsx
Labels: bug

#2411 Release v0.24.0 - ng & React
  angular-workspace/ng14/package-lock.json
  angular-workspace/ng14/package.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  angular-workspace/ng15/package-lock.json
  angular-workspace/ng15/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  angular-workspace/ng16/package-lock.json
  angular-workspace/ng16/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  angular-workspace/ng17/package-lock.json
  angular-workspace/ng17/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
  stencil-workspace/src/components/modus-text-input/readme.md
Labels: skip-changelog

#2413 Release v0.24.1
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#2415 Release v0.24.1 - ng & React
  angular-workspace/ng14/package-lock.json
  angular-workspace/ng14/package.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/package-lock.json
  angular-workspace/ng15/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/package-lock.json
  angular-workspace/ng16/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/package-lock.json
  angular-workspace/ng17/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: skip-changelog

#2416 Dropdown: Add control to docs
  stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown.stories.tsx
Labels: docs

#2374 Modal: Accessibility updates
  stencil-workspace/src/components/modus-modal/modus-modal.e2e.ts
  stencil-workspace/src/components/modus-modal/modus-modal.spec.ts
  stencil-workspace/src/components/modus-modal/modus-modal.tsx
  stencil-workspace/storybook/stories/components/modus-modal/modus-modal.stories.tsx
Labels: bug, accessibility

#2359 Toast: make 'role' configurable.
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-toast/modus-toast.spec.ts
  stencil-workspace/src/components/modus-toast/modus-toast.tsx
  stencil-workspace/src/components/modus-toast/readme.md
  stencil-workspace/storybook/stories/components/modus-toast/modus-toast-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-toast/modus-toast.stories.tsx
Labels: accessibility

#2423 Docs: badges (counter) Canvas demo to use numbers (not text)
  stencil-workspace/storybook/stories/components/modus-badge/modus-badge.stories.tsx
Labels: docs

#2417 Navbar : Help Icon tab navigation
  stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
Labels: bug, modus-navbar

#2407 Accordion: Style Fixes
  stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.e2e.ts
  stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.scss
  stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.spec.ts
  stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.tsx
  stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.vars.scss
  stencil-workspace/src/global/themes.scss
Labels: bug, modus-accordion

#2424 Navbar: Add Badge icon to Notification Button
  stencil-workspace/src/components/modus-badge/modus-badge.scss
  stencil-workspace/src/components/modus-badge/readme.md
  stencil-workspace/src/components/modus-navbar/modus-navbar.scss
  stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
  stencil-workspace/src/components/modus-navbar/readme.md
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
Labels: modus-navbar, modus-badge

#2427 Navbar: add missing notificationCount definition
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  stencil-workspace/src/components.d.ts
Labels: bug, modus-navbar

#2428 Release v0.25.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#2429 Release v0.25.0 - ng & React
  angular-workspace/ng14/package-lock.json
  angular-workspace/ng14/package.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/package-lock.json
  angular-workspace/ng15/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/package-lock.json
  angular-workspace/ng16/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/package-lock.json
  angular-workspace/ng17/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: skip-changelog

#2431 Add Axe Accessibility check GitHub Action
  .github/workflows/axe-linter.yml
Labels: github_actions

#2436 Radio Group: Update docs
  stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group.stories.tsx
Labels: docs

#2434 Radio Group: Label mismatch with radio button
  stencil-workspace/src/components/modus-radio-group/modus-radio-button.tsx
Labels: accessibility

#2421 Toast: Fix accessibility for the dismiss/close button
  stencil-workspace/src/components/modus-toast/modus-toast.scss
  stencil-workspace/src/components/modus-toast/modus-toast.spec.ts
  stencil-workspace/src/components/modus-toast/modus-toast.tsx
Labels: 2, accessibility

#2445 DevOps: Build Stencil Dist Files in Dev Mode
  stencil-workspace/stencil.config.ts
Labels: 1, devOps

#2450 Switch: Set aria-checked value to "true" and "false"
  stencil-workspace/src/components/modus-switch/modus-switch.e2e.ts
  stencil-workspace/src/components/modus-switch/modus-switch.spec.tsx
  stencil-workspace/src/components/modus-switch/modus-switch.tsx
Labels: bug, accessibility

#2454 Button-Group: Add `role="group"`
  stencil-workspace/src/components/modus-button-group/modus-button-group.e2e.ts
  stencil-workspace/src/components/modus-button-group/modus-button-group.spec.ts
  stencil-workspace/src/components/modus-button-group/modus-button-group.tsx
  stencil-workspace/storybook/stories/components/modus-button-group/modus-button-group-storybook-docs.mdx
Labels: bug, accessibility

#2456 Dropdown: Fix disabled behavior on dropdown element
  stencil-workspace/src/components/modus-dropdown/modus-dropdown.e2e.ts
  stencil-workspace/src/components/modus-dropdown/modus-dropdown.tsx
Labels: bug

#2460 Release v0.26.1
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#2462 Release v0.26.1 - ng & React
  angular-workspace/ng14/package-lock.json
  angular-workspace/ng14/package.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/package-lock.json
  angular-workspace/ng15/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/package-lock.json
  angular-workspace/ng16/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/package-lock.json
  angular-workspace/ng17/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: skip-changelog

#2474 Dropdown: Prevent pointer events from occurring when disabled.
  stencil-workspace/src/components/modus-dropdown/modus-dropdown.e2e.ts
  stencil-workspace/src/components/modus-dropdown/modus-dropdown.scss
  stencil-workspace/src/components/modus-dropdown/modus-dropdown.tsx
Labels: bug

#2472 Toast: Dismiss Button Style Improvement
  stencil-workspace/src/components/modus-toast/modus-toast.scss
  stencil-workspace/src/components/modus-toast/modus-toast.tsx
Labels: bug

#2383 Tabs: Fix issue where selecting a tab in a set with no active tab errors out
  stencil-workspace/src/components/modus-tabs/modus-tabs.e2e.ts
  stencil-workspace/src/components/modus-tabs/modus-tabs.tsx
Labels: bug, modus-tabs

#2449 Tooltip: fix issue with tooltip creating a new line when multiple buttons are in a row
  stencil-workspace/src/components/modus-tooltip/modus-tooltip.scss
Labels: bug, modus-tooltip

#2481 Release v0.27.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#2483 Release v0.27.0 - ng & React
  angular-workspace/ng14/package-lock.json
  angular-workspace/ng14/package.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/package-lock.json
  angular-workspace/ng15/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/package-lock.json
  angular-workspace/ng16/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/package-lock.json
  angular-workspace/ng17/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
  stencil-workspace/src/components/modus-switch/readme.md
Labels: skip-changelog
