Repository trimble-oss/modus-web-components, pull requests merged in 2024-10, with the labels that each got.

#2889 Navbar: profile menu icon background to be transparent
  stencil-workspace/src/components/modus-navbar/modus-navbar.scss
  stencil-workspace/src/components/modus-navbar/profile-menu/modus-navbar-profile-menu.scss
Labels: bug

#2901 List : Add missing property(leftIcon) to documentation
  stencil-workspace/storybook/stories/components/modus-list/modus-list-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-list/modus-list.stories.tsx
Labels: docs

#2905 Side Navigation: Update prop name to menuIcon from menuIconUrl
  stencil-workspace/storybook/stories/components/modus-side-navigation/modus-side-navigation-storybook-docs.mdx
Labels: docs

#2906 DropDown : Add customPlacement to docs
  stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown.stories.tsx
Labels: docs

#2915 Autocomplete: custom options duplicate chips issue
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.e2e.ts
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
Labels: bug

#2925 FileDropzone : Fix reset button loading time
  stencil-workspace/src/components/modus-button/readme.md
  stencil-workspace/src/components/modus-file-dropzone/modus-file-dropzone.e2e.ts
  stencil-workspace/src/components/modus-file-dropzone/readme.md
  stencil-workspace/src/sample.html
  stencil-workspace/storybook/stories/components/modus-accordion/modus-accordion.stories.tsx
  stencil-workspace/storybook/stories/components/modus-breadcrumb/modus-breadcrumb.stories.tsx
  stencil-workspace/storybook/stories/components/modus-card/modus-card.stories.tsx
  stencil-workspace/storybook/stories/components/modus-checkbox/modus-checkbox-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-checkbox/modus-checkbox.stories.tsx
  stencil-workspace/storybook/stories/components/modus-chip/modus-chip-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
  stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown.stories.tsx
  stencil-workspace/storybook/stories/components/modus-file-dropzone/modus-file-dropzone-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-list/modus-list.stories.tsx
  stencil-workspace/storybook/stories/components/modus-message/modus-message-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-message/modus-message.stories.tsx
  stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group.stories.tsx
  stencil-workspace/storybook/stories/components/modus-select/modus-select-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-select/modus-select.stories.tsx
  stencil-workspace/storybook/stories/components/modus-side-navigation/modus-side-navigation-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-side-navigation/modus-side-navigation.stories.tsx
  stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input.stories.tsx
  stencil-workspace/storybook/stories/components/modus-time-picker/modus-time-picker-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-time-picker/modus-time-picker.stories.tsx
  stencil-workspace/storybook/stories/components/modus-utility-panel/modus-utility-panel-storybook-docs.mdx
  stencil-workspace/storybook/stories/framework-integrations/angular.stories.mdx
Labels: skip-changelog

#2930 Release v0.40.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog
