Repository trimble-oss/modus-web-components, pull requests merged in 2024-12, with the labels that each got.

#3055 Modus Button: adding missing focus-visible style based on color variant
  stencil-workspace/src/components/modus-button/modus-button.scss
  stencil-workspace/src/components/modus-button/modus-button.vars.scss
Labels: team-navi-gators

#2980 Navbar: Add css cursor pointers to primary and second logo
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-navbar/modus-navbar.e2e.ts
  stencil-workspace/src/components/modus-navbar/modus-navbar.models.ts
  stencil-workspace/src/components/modus-navbar/modus-navbar.scss
  stencil-workspace/src/components/modus-navbar/product-logo/modus-navbar-product-logo.tsx
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
Labels: modus-navbar

#3062 Message: message text color code fix in dark mode
  stencil-workspace/src/global/themes.scss
Labels: bug, modus-message

#3056 Table: language translation based on RFC 5646
  stencil-workspace/src/components/modus-table/modus-table.e2e.ts
  stencil-workspace/src/components/modus-table/modus-table.tsx
  stencil-workspace/src/components/modus-table/parts/columnHeader/modus-table-column-header-label.tsx
  stencil-workspace/src/components/modus-table/parts/modus-table-pagination.tsx
  stencil-workspace/src/lang/translations.ts
Labels: breaking-change

#3063 Utility Panel: Content is not pushed in the default expanded state
  stencil-workspace/src/components/modus-utility-panel/modus-utility-panel.spec.ts
  stencil-workspace/src/components/modus-utility-panel/modus-utility-panel.tsx
Labels: bug

#3084 Release v1.1.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
  stencil-workspace/storybook/package-lock.json
  stencil-workspace/storybook/package.json
  stencil-workspace/storybook/public/storybook-styles.css
Labels: skip-changelog

#3085 Release v110 - React & ng
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: skip-changelog
