Repository trimble-oss/modus-web-components, pull requests merged in 2024-06, with the labels that each got.

#2559 Set: `forceConsistentCasingInFileNames` rule to true (tsconfig)
  stencil-workspace/tsconfig.json
Labels: 1, devOps, skip-changelog

#2086 Navbar: Wrap link item text
  stencil-workspace/src/components/modus-navbar/profile-menu/modus-navbar-profile-menu.scss
Labels: blocked, modus-navbar

#2532 Table: Optional chaining for tableCore `onDataChange` initialization error
  stencil-workspace/src/components/modus-table/modus-table.tsx
Labels: bug, modus-table

#2566 Inputs: Set border for disabled state to transparent
  stencil-workspace/src/components/modus-date-input/modus-date-input.scss
  stencil-workspace/src/components/modus-number-input/modus-number-input.scss
  stencil-workspace/src/components/modus-select/modus-select.scss
  stencil-workspace/src/components/modus-text-input/modus-text-input.scss
  stencil-workspace/src/components/modus-time-picker/modus-time-picker.scss
Labels: modus-date-picker, number-input, modus-time-picker, modus-input, modus-select

#2539 Tooltip: performance optimization
  stencil-workspace/src/components/modus-navbar/modus-navbar.e2e.ts
  stencil-workspace/src/components/modus-tooltip/modus-tooltip.e2e.ts
  stencil-workspace/src/components/modus-tooltip/modus-tooltip.tsx
Labels: bug, modus-tooltip

#2523 Content Tree: Keyboard navigation to move items
  stencil-workspace/src/components/modus-content-tree/modus-content-tree.spec.tsx
  stencil-workspace/src/components/modus-content-tree/modus-content-tree.types.tsx
  stencil-workspace/src/components/modus-content-tree/modus-tree-view-item/modus-tree-view-item.tsx
  stencil-workspace/src/components/modus-content-tree/modus-tree-view/modus-tree-view.tsx
Labels: modus-tree-view

#2576 Fix type mismatch with core HTMLStencilElement
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-button-group/modus-button-group.tsx
  stencil-workspace/src/components/modus-content-tree/modus-tree-view-item/modus-tree-view-item.tsx
  stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
  stencil-workspace/src/components/modus-text-input/readme.md
  stencil-workspace/src/components/modus-toast/modus-toast.tsx
  stencil-workspace/src/components/modus-toast/readme.md
Labels: bug

#2574 Navbar: Remove modus navbar main menu border
  stencil-workspace/src/components/modus-navbar/main-menu/modus-navbar-main-menu.scss
Labels: modus-navbar

#2577 Release v0.30.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-icons/readme.md
  stencil-workspace/src/components/modus-tooltip/modus-tooltip.tsx
Labels: skip-changelog

#2578 Release v0.30.0 - ng & React
  angular-workspace/ng14/package-lock.json
  angular-workspace/ng14/package.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/package-lock.json
  angular-workspace/ng15/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/package-lock.json
  angular-workspace/ng16/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/package-lock.json
  angular-workspace/ng17/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: skip-changelog

#2580 Inputs: Fix focus border CSS styles
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.scss
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.vars.scss
  stencil-workspace/src/components/modus-date-input/modus-date-input.scss
  stencil-workspace/src/components/modus-date-input/modus-date-input.vars.scss
  stencil-workspace/src/components/modus-number-input/modus-number-input.scss
  stencil-workspace/src/components/modus-number-input/modus-number-input.vars.scss
  stencil-workspace/src/components/modus-select/modus-select.scss
  stencil-workspace/src/components/modus-select/modus-select.vars.scss
  stencil-workspace/src/components/modus-text-input/modus-text-input.scss
  stencil-workspace/src/components/modus-text-input/modus-text-input.vars.scss
  stencil-workspace/src/components/modus-time-picker/modus-time-picker.scss
  stencil-workspace/src/components/modus-time-picker/modus-time-picker.vars.scss
  stencil-workspace/src/global/themes.scss
Labels: bug

#2582 Table: Custom sorting function documentation for storybook
  stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
Labels: modus-table

#2593 Docs: Fix broken link to Modus Icons site
  stencil-workspace/storybook/stories/components/modus-icons/modus-icons-storybook-docs.mdx
Labels: docs

#2587 Textarea: Input Style Fixes
  stencil-workspace/src/components/modus-textarea-input/modus-textarea-input.scss
  stencil-workspace/src/components/modus-textarea-input/modus-textarea-input.spec.tsx
  stencil-workspace/src/components/modus-textarea-input/modus-textarea-input.tsx
  stencil-workspace/src/components/modus-textarea-input/modus-textarea-input.vars.scss
  stencil-workspace/storybook/stories/components/modus-textarea-input/modus-textarea-input-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-textarea-input/modus-textarea-input.stories.tsx
Labels: bug

#2590 Autoformats code with Prettier
  .prettierignore
  .vscode/settings.json
Labels: 1, devOps, skip-changelog

#2599 Docs: Fix Toolbar Storybook
  stencil-workspace/src/components/modus-toolbar/modus-toolbar.tsx
  stencil-workspace/src/components/modus-toolbar/readme.md
  stencil-workspace/src/components/modus-tooltip/readme.md
  stencil-workspace/storybook/stories/components/modus-toolbar/modus-toolbar-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-toolbar/modus-toolbar.stories.tsx
Labels: bug

#2605 Release v0.31.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#2607 Release v0.31.0 - ng & React
  angular-workspace/ng14/package-lock.json
  angular-workspace/ng14/package.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/package-lock.json
  angular-workspace/ng15/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/package-lock.json
  angular-workspace/ng16/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/package-lock.json
  angular-workspace/ng17/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: skip-changelog

#2568 Table: API for handling cell edit
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-table/modus-table.tsx
  stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-main/modus-table-cell-main.tsx
  stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-main/readme.md
  stencil-workspace/src/components/modus-table/readme.md
  stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
Labels: modus-table

#2621 Release v0.32.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#2622 Release v0.32.0 - ng & React
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: skip-changelog

#2631 Textarea: readonly state CSS fix
  stencil-workspace/src/components/modus-textarea-input/modus-textarea-input.scss
Labels: bug

#2638 BreadCrumb: Add handling of event "crumbClick"
  stencil-workspace/storybook/stories/components/modus-breadcrumb/modus-breadcrumb.stories.tsx
Labels: 1, bug

#2641 AutoComplete: Cleanup StoryBook examples
  stencil-workspace/storybook/stories/components/modus-autocomplete/modus-autocomplete-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-autocomplete/modus-autocomplete.stories.tsx
Labels: docs

#2643 AutoComplete: size property update for storybook
  stencil-workspace/storybook/stories/components/modus-autocomplete/modus-autocomplete-storybook-docs.mdx
Labels: docs

#2644 Autocomplete: Shift down to open menu items
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
Labels: bug, modus-autocomplete

#2648 Release v0.33.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
  stencil-workspace/storybook/stories/components/modus-breadcrumb/modus-breadcrumb-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-breadcrumb/modus-breadcrumb.stories.tsx
Labels: skip-changelog

#2649 Release - React & Angular v0.33.0
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-button/readme.md
  stencil-workspace/src/components/modus-date-picker/readme.md
  stencil-workspace/src/components/modus-list-item/readme.md
  stencil-workspace/src/components/modus-list/readme.md
  stencil-workspace/src/components/modus-navbar/readme.md
  stencil-workspace/src/components/modus-text-input/readme.md
Labels: skip-changelog

#2650 Bump MWC version (Angular Workspace)
  angular-workspace/ng14/package-lock.json
  angular-workspace/ng14/package.json
  angular-workspace/ng15/package-lock.json
  angular-workspace/ng15/package.json
  angular-workspace/ng16/package-lock.json
  angular-workspace/ng16/package.json
  angular-workspace/ng17/package-lock.json
  angular-workspace/ng17/package.json
  stencil-workspace/storybook/stories/components/modus-number-input/modus-number-input-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-number-input/modus-number-input.stories.tsx
  stencil-workspace/storybook/stories/components/modus-pagination/modus-pagination-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-pagination/modus-pagination.stories.tsx
  stencil-workspace/storybook/stories/components/modus-progress-bar/modus-progress-bar-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-progress-bar/modus-progress-bar.stories.tsx
  stencil-workspace/storybook/stories/components/modus-sentiment-scale/modus-sentiment-scale-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-sentiment-scale/modus-sentiment-scale.stories.tsx
  stencil-workspace/storybook/stories/components/modus-slider/modus-slider.stories.tsx
  stencil-workspace/storybook/stories/components/modus-spinner/modus-spinner.stories.tsx
  stencil-workspace/storybook/stories/components/modus-switch/modus-switch-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-switch/modus-switch.stories.tsx
  stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
  stencil-workspace/storybook/stories/components/modus-tabs/modus-tabs-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-tabs/modus-tabs.stories.tsx
  stencil-workspace/storybook/stories/components/modus-tooltip/modus-tooltip-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-tooltip/modus-tooltip.stories.tsx
Labels: skip-changelog

#2653 Docs: Fix accessibilty issues on Buttons Canvas Demo
  stencil-workspace/storybook/stories/components/modus-button-group/modus-button-group-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-button/modus-button.stories.tsx
  stencil-workspace/storybook/stories/components/modus-card/modus-card-storybook-docs.mdx
Labels: docs

#2655 Minor Docs Fixes
  .cspell.json
  stencil-workspace/src/components/modus-utility-panel/modus-utility-panel.scss
  stencil-workspace/storybook/stories/components/modus-accordion/modus-accordion-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-autocomplete/modus-autocomplete-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-autocomplete/modus-autocomplete.stories.tsx
  stencil-workspace/storybook/stories/components/modus-pagination/modus-pagination-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input-storybook-docs.mdx
Labels: docs

#2659 Fix Angular build compilation error
  stencil-workspace/src/interfaces.d.ts
Labels: bug

#2662 Release v0.33.1
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog
