Repository trimble-oss/modus-web-components, pull requests merged in 2024-03, with the labels that each got.

#2236 Accordion: Use Modus Icons for Expand/Collapse
  stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.e2e.ts
  stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.scss
  stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.spec.ts
  stencil-workspace/src/components/modus-accordion-item/modus-accordion-item.tsx
  stencil-workspace/src/components/modus-accordion/modus-accordion.scss
  stencil-workspace/src/components/modus-accordion/modus-accordion.tsx
Labels: bug

#2231 Sentiment Scale: Remove hover state for disabled state
  stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.scss
Labels: bug, accessibility

#2257 Chips: Use button element
  stencil-workspace/src/components/modus-chip/modus-chip.scss
  stencil-workspace/src/components/modus-chip/modus-chip.spec.ts
  stencil-workspace/src/components/modus-chip/modus-chip.tsx
Labels: accessibility

#2230 Data Table: Remove row action menu dropdown border
  stencil-workspace/src/components/modus-data-table/parts/modus-data-table-row-action-dropdown.tsx
Labels: bug

#2262 Release v0.20.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#2267 Release v0.20.0 - ng & React
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: skip-changelog

#2269 Button: Make `aria-disabled` buttons look disabled (CSS fix)
  stencil-workspace/src/components/modus-button/modus-button.scss
Labels: 1, bug

#2278 Docs: Various minor fixes
  .cspell.json
  angular-workspace/test-ng14/package-lock.json
  angular-workspace/test-ng14/package.json
  angular-workspace/test-ng15/package-lock.json
  angular-workspace/test-ng15/package.json
  angular-workspace/test-web-components/package-lock.json
  angular-workspace/test-web-components/package.json
  react-workspace/test-react-v17/package-lock.json
  react-workspace/test-react-v17/package.json
  react-workspace/test-react-v18/package-lock.json
  react-workspace/test-react-v18/package.json
  react-workspace/test-web-components/package-lock.json
  react-workspace/test-web-components/package.json
  stencil-workspace/src/components/modus-content-tree/modus-content-tree.spec.tsx
  stencil-workspace/src/components/modus-side-navigation/modus-side-navigation.spec.tsx
  stencil-workspace/src/components/modus-time-picker/modus-time-picker.spec.tsx
  stencil-workspace/src/components/modus-time-picker/modus-time-picker.tsx
Labels: docs

#2279 Dropdown: Remove unnecessary `role="listbox"`
  stencil-workspace/src/components/modus-dropdown/modus-dropdown.spec.ts
  stencil-workspace/src/components/modus-dropdown/modus-dropdown.tsx
  stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown.stories.tsx
Labels: accessibility

#2223 Table: column visibility dropdown list too long
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-table/parts/panel/modus-table-columns-visibility/modus-table-columns-visibility.scss
  stencil-workspace/src/components/modus-table/parts/panel/modus-table-columns-visibility/modus-table-columns-visibility.tsx
  stencil-workspace/src/components/modus-table/parts/panel/modus-table-dropdown-menu/modus-table-dropdown-menu.tsx
Labels: bug

#2268 Alert: Update max character length to 300
  stencil-workspace/src/components/modus-alert/modus-alert.e2e.ts
  stencil-workspace/src/components/modus-alert/modus-alert.tsx
Labels: alert

#2285 Docs: update table column visibility for max height
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  stencil-workspace/src/components/modus-table/parts/panel/modus-table-columns-visibility/readme.md
Labels: table, docs

#2286 Table: Update how sortFn is defaulted to account for immutable column
  stencil-workspace/src/components/modus-table/modus-table.tsx
Labels: bug, table

#2290 Angular: Updating output targets
  .github/workflows/publish-angular.yml
  angular-workspace/ng14/package-lock.json
  angular-workspace/ng14/package.json
  angular-workspace/ng15/package-lock.json
  angular-workspace/ng15/package.json
  angular-workspace/ng16/package-lock.json
  angular-workspace/ng16/package.json
  angular-workspace/ng17/package-lock.json
  angular-workspace/ng17/package.json
  package.json
  stencil-workspace/src/components/modus-table/parts/row/actions/modus-table-row-actions/modus-table-row-actions.tsx
  stencil-workspace/stencil.config.ts
Labels: bug, angular

#2289 Release v0.21.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#2301 Angular: Update components.d.ts properly
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-table/parts/row/actions/modus-table-row-actions/readme.md
Labels: bug

#2302 Release v0.21.1
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#2303 Release v0.21.1 - ng & React
  angular-workspace/ng14/package-lock.json
  angular-workspace/ng14/package.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/angular-component-lib/utils.ts
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/boolean-value-accessor.ts
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/index.ts
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/select-value-accessor.ts
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/text-value-accessor.ts
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/value-accessor.ts
  angular-workspace/ng15/package-lock.json
  angular-workspace/ng15/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/angular-component-lib/utils.ts
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/boolean-value-accessor.ts
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/index.ts
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/select-value-accessor.ts
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/text-value-accessor.ts
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/value-accessor.ts
  angular-workspace/ng16/package-lock.json
  angular-workspace/ng16/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/angular-component-lib/utils.ts
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/boolean-value-accessor.ts
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/index.ts
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/select-value-accessor.ts
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/text-value-accessor.ts
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/value-accessor.ts
  angular-workspace/ng17/package-lock.json
  angular-workspace/ng17/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/angular-component-lib/utils.ts
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/boolean-value-accessor.ts
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/index.ts
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/select-value-accessor.ts
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/text-value-accessor.ts
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/value-accessor.ts
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: skip-changelog

#2288 Content Tree: Add a borderless variant
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-content-tree/modus-content-tree.e2e.ts
  stencil-workspace/src/components/modus-content-tree/modus-content-tree.types.tsx
  stencil-workspace/src/components/modus-content-tree/modus-tree-view-item/modus-tree-view-item.scss
  stencil-workspace/src/components/modus-content-tree/modus-tree-view-item/modus-tree-view-item.tsx
  stencil-workspace/src/components/modus-content-tree/modus-tree-view/modus-tree-view.tsx
  stencil-workspace/src/components/modus-content-tree/modus-tree-view/readme.md
  stencil-workspace/storybook/stories/components/modus-content-tree/modus-content-tree-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-content-tree/modus-content-tree.stories.tsx
  stencil-workspace/storybook/stories/components/modus-date-picker/modus-date-picker.stories.tsx
Labels: e-builder-submission, team-e-builder, content-tree

#2316 Slider: Accessibility fixes
  stencil-workspace/src/components/modus-slider/modus-slider.spec.ts
  stencil-workspace/src/components/modus-slider/modus-slider.tsx
  stencil-workspace/storybook/stories/components/modus-slider/modus-slider.stories.tsx
Labels: bug, accessibility

#2129 Table: Update to disable automatic resetting of page index
  stencil-workspace/src/components/modus-table/modus-table.core.tsx
  stencil-workspace/src/components/modus-table/modus-table.e2e.ts
  stencil-workspace/src/components/modus-table/modus-table.tsx
  stencil-workspace/src/components/modus-table/parts/modus-table-pagination.tsx
Labels: bug, table

#2328 Docs: Slider docs fixes
  stencil-workspace/storybook/stories/components/modus-slider/modus-slider-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-slider/modus-slider.stories.tsx
Labels: docs

#2330 Select: Fix for Labels not being linked to the selects
  stencil-workspace/src/components/modus-select/modus-select.spec.ts
  stencil-workspace/src/components/modus-select/modus-select.tsx
  stencil-workspace/storybook/stories/components/modus-select/modus-select-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-select/modus-select.stories.tsx
Labels: bug, accessibility

#2333 Docs: Fix some accessibility 'incomplete' (warnings) in Canvas demos
  stencil-workspace/storybook/stories/components/modus-date-picker/modus-date-picker.stories.tsx
  stencil-workspace/storybook/stories/components/modus-number-input/modus-number-input.stories.tsx
  stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input.stories.tsx
Labels: docs

#2348 Docs: Add link to Netlify from front page
  stencil-workspace/storybook/stories/introduction/welcome.stories.mdx
Labels: 1, docs

#2350 Docs: fix broken radio-group component examples
  stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group-storybook-docs.mdx
Labels: docs

#2344 Date Picker: Fixes a few usability / accessibility issues
  stencil-workspace/src/components/modus-date-picker/modus-date-picker.scss
  stencil-workspace/src/components/modus-date-picker/modus-date-picker.tsx
Labels: 1, bug, accessibility

#2276 Navbar: Remove Pressed State for the icon button after popup is closed
  stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
Labels: e-builder-submission, team-e-builder, navbar

#2266 Table: update column header text to sort and display a tooltip
  stencil-workspace/src/components/modus-table/modus-table.e2e.ts
  stencil-workspace/src/components/modus-table/modus-table.scss
  stencil-workspace/src/components/modus-table/parts/columnHeader/modus-table-column-header-label.tsx
  stencil-workspace/src/components/modus-table/parts/columnHeader/modus-table-column-header.tsx
  stencil-workspace/src/components/modus-tooltip/modus-tooltip.tsx
Labels: e-builder-submission, team-e-builder

#2307 Navbar: Add `aria-label` to Search and Help buttons
  stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
Labels: 1, bug, accessibility

#2337 Text Input: Add HTML5 `pattern` attribute
  stencil-workspace/src/components/modus-text-input/modus-text-input.e2e.ts
  stencil-workspace/src/components/modus-text-input/modus-text-input.spec.tsx
  stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
  stencil-workspace/src/components/modus-text-input/readme.md
  stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input.stories.tsx
Labels: text-input

#2354 Input: Add primary-font to input elements designed to display text
  stencil-workspace/src/components/modus-date-input/modus-date-input.scss
  stencil-workspace/src/components/modus-date-picker/modus-date-picker.scss
  stencil-workspace/src/components/modus-number-input/modus-number-input.scss
  stencil-workspace/src/components/modus-text-input/modus-text-input.scss
  stencil-workspace/src/components/modus-time-picker/modus-time-picker.scss
Labels: bug, date-picker, trimble-technology, number-input, text-input

#2362 Release v0.23.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#2373 Release v0.23.0 - ng & React
  angular-workspace/ng14/package-lock.json
  angular-workspace/ng14/package.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  angular-workspace/ng15/package-lock.json
  angular-workspace/ng15/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  angular-workspace/ng16/package-lock.json
  angular-workspace/ng16/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  angular-workspace/ng17/package-lock.json
  angular-workspace/ng17/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-text-input/readme.md
Labels: skip-changelog
