Repository trimble-oss/modus-web-components, pull requests merged in 2024-09, with the labels that each got.

#2832 Fix for Alert: Warning alert icon is incorrect color (light mode)
  stencil-workspace/src/components/modus-alert/modus-alert.scss
  stencil-workspace/src/components/modus-alert/modus-alert.vars.scss
  stencil-workspace/src/global/themes.scss
  stencil-workspace/src/icons/svgs/icon-error.tsx
  stencil-workspace/src/icons/svgs/icon-warning.tsx
Labels: bug

#2844 Docs: Add Accessibility page
  .github/workflows/super-linter.yml
  stencil-workspace/storybook/.storybook/preview.js
  stencil-workspace/storybook/stories/introduction/accessibility.stories.mdx
Labels: accessibility, docs

#2845 Datepicker: Update datepicker position logic
  stencil-workspace/src/components/modus-date-picker/modus-date-picker.tsx
  stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-editor/modus-table-cell-editor.scss
  stencil-workspace/storybook/stories/components/modus-date-picker/modus-date-picker-storybook-docs.mdx
Labels: bug

#2865 Release v0.38.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#2866 Release v0.38.0 - ng & React
  angular-workspace/ng14/package-lock.json
  angular-workspace/ng14/package.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/package-lock.json
  angular-workspace/ng15/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/package-lock.json
  angular-workspace/ng16/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/package-lock.json
  angular-workspace/ng17/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: skip-changelog

#2873 Autocomplete: Update or reset selection on value change in multiselect mode
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.e2e.ts
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
Labels: bug

#2875 Buttongroup: Handle selection reset for single and multiple selections
  stencil-workspace/src/components/modus-button-group/modus-button-group.constants.ts
  stencil-workspace/src/components/modus-button-group/modus-button-group.e2e.ts
  stencil-workspace/src/components/modus-button-group/modus-button-group.spec.ts
  stencil-workspace/src/components/modus-button-group/modus-button-group.tsx
  stencil-workspace/src/components/modus-number-input/readme.md
Labels: bug

#2879 Release v0.39.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#2880 Release v0.39.0 - ng & React
  angular-workspace/ng14/package-lock.json
  angular-workspace/ng14/package.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/package-lock.json
  angular-workspace/ng15/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/package-lock.json
  angular-workspace/ng16/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/package-lock.json
  angular-workspace/ng17/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: skip-changelog
