Repository trimble-oss/modus-web-components, pull requests merged in 2024-01, with the labels that each got.

#1958 List: Add support for sub-text in list item
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-list-item/modus-list-item.e2e.ts
  stencil-workspace/src/components/modus-list-item/modus-list-item.scss
  stencil-workspace/src/components/modus-list-item/modus-list-item.spec.ts
  stencil-workspace/src/components/modus-list-item/modus-list-item.tsx
  stencil-workspace/src/components/modus-list-item/readme.md
  stencil-workspace/storybook/stories/components/modus-list/modus-list-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-list/modus-list.stories.tsx
Labels: team-e-builder

#2000 Release v0.11.0 - React & Angular
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/test-web-components/package-lock.json
  angular-workspace/test-web-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
  react-workspace/test-web-components/package-lock.json
  react-workspace/test-web-components/package.json
Labels: 1, skip-changelog

#1993 Modus Autocomplete: Adding @watch decorator to value property
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.e2e.ts
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.spec.ts
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
  stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
Labels: team-e-builder

#2015 Bump follow-redirects to 1.15.4
  .github/workflows/issue-thanks.yml
  angular-workspace/ng16/package-lock.json
  angular-workspace/test-ng14/package-lock.json
  angular-workspace/test-ng14/package.json
  angular-workspace/test-ng15/package-lock.json
  angular-workspace/test-ng15/package.json
  angular-workspace/test-web-components/package-lock.json
  react-workspace/test-react-v17/package-lock.json
  react-workspace/test-react-v17/package.json
  react-workspace/test-react-v18/package-lock.json
  react-workspace/test-react-v18/package.json
  react-workspace/test-web-components/package-lock.json
Labels: dependencies

#1972 Modus Autocomplete - add disable close on select property
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.e2e.ts
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
  stencil-workspace/src/components/modus-autocomplete/readme.md
  stencil-workspace/storybook/stories/components/modus-autocomplete/modus-autocomplete-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-autocomplete/modus-autocomplete.stories.tsx
Labels: team-e-builder

#2022 Release v0.12.0
  .github/workflows/azure-static-web-apps-deploy.yml
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: 1, skip-changelog

#2030 Release v0.12.0 for React and Angular
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: 1, skip-changelog

#2031 Update release-drafter.yml
  .github/release-drafter.yml
Labels: 1, devOps

#1981 Modus Table: Update checkbox size based on density
  stencil-workspace/src/components/modus-table/models/table-context.models.ts
  stencil-workspace/src/components/modus-table/modus-table.e2e.ts
  stencil-workspace/src/components/modus-table/modus-table.scss
  stencil-workspace/src/components/modus-table/modus-table.tsx
  stencil-workspace/src/components/modus-table/parts/modus-table-body.tsx
  stencil-workspace/src/components/modus-table/parts/modus-table-footer.tsx
  stencil-workspace/src/components/modus-table/parts/row/selection/modus-table-cell-checkbox.tsx
  stencil-workspace/src/components/modus-table/parts/row/selection/modus-table-header-checkbox.tsx
  stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
Labels: team-e-builder

#1992 Modus Autocomplete: Disable brower's autocomplete on text input
  angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.e2e.ts
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.spec.ts
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
  stencil-workspace/src/components/modus-text-input/modus-text-input.e2e.ts
  stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
  stencil-workspace/src/components/modus-text-input/readme.md
  stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-text-input/modus-text-input.stories.tsx
Labels: team-e-builder

#2042 Only deploy to modus-web-components.trimble.com on release
  .github/workflows/azure-static-web-apps-deploy.yml
  .vscode/settings.json
  README.md
  stencil-workspace/storybook/stories/framework-integrations/angular.stories.mdx
  stencil-workspace/storybook/stories/framework-integrations/react.stories.mdx
  stencil-workspace/storybook/stories/introduction/contributing.stories.mdx
  stencil-workspace/storybook/stories/introduction/welcome.stories.mdx
Labels: devOps

#2041 Navbar: add tab index to logo and trigger productLogoClick with keyboard
  stencil-workspace/src/components/modus-navbar/product-logo/modus-navbar-product-logo.tsx
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
Labels: e-builder-submission, team-e-builder

#2049 Release v0.13.0
  .cspell.json
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: 1, skip-changelog

#2050 v0.13.0 - Update version for React & Angular release
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: 1, skip-changelog

#1994 Modus table - Row Action - Row Dropdown position
  stencil-workspace/src/components/modus-table/parts/row/actions/modus-table-row-actions-menu/modus-table-row-actions-menu.tsx
Labels: bug

#2037 Autocomplete: unable to search when disable-close-on-sect is enable. it cannot filter the options
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
Labels: bug, e-builder-submission, team-e-builder

#2061 Autocomplete: Use input `type="search"`
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.spec.ts
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
Labels: accessibility

#2080 Docs: Add aria-label to icon-only buttons
  stencil-workspace/storybook/stories/components/modus-button/modus-button-storybook-docs.mdx
Labels: 1, accessibility, docs

#2083 Alert: Add `role` and `aria-label` to Close/dismiss button
  stencil-workspace/src/components/modus-alert/modus-alert.tsx
Labels: bug, accessibility

#2084 Docs: Move Radio Group to User Inputs section
  stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group.stories.tsx
Labels: 1, docs

#2067 Autocomplete: Hitting Space should also select a focused option as well as hitting Enter
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.e2e.ts
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.spec.ts
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
  stencil-workspace/src/utils/utils.spec.ts
  stencil-workspace/src/utils/utils.ts
Labels: accessibility

#2001 Table: Set table-layout to fixed for full width table
  stencil-workspace/src/components/modus-table/modus-table.e2e.ts
  stencil-workspace/src/components/modus-table/modus-table.tsx
Labels: bug
