Repository trimble-oss/modus-web-components, pull requests merged in 2024-07, with the labels that each got.

#2654 Table: Number 0 is visible in the table cells
  stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-main/modus-table-cell-main.tsx
Labels: bug

#2677 Toolbar: Icon only buttons do not have aria-labels
  stencil-workspace/src/components/modus-toolbar/modus-toolbar.spec.ts
  stencil-workspace/src/components/modus-toolbar/modus-toolbar.tsx
  stencil-workspace/storybook/stories/components/modus-toolbar/modus-toolbar-storybook-docs.mdx
Labels: bug, accessibility

#2686 Modal: Add Full Screen
  stencil-workspace/src/components/modus-modal/modus-modal.e2e.ts
  stencil-workspace/src/components/modus-modal/modus-modal.scss
  stencil-workspace/src/components/modus-modal/modus-modal.tsx
  stencil-workspace/src/components/modus-modal/readme.md
  stencil-workspace/storybook/stories/components/modus-modal/modus-modal-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-modal/modus-modal.stories.tsx
Labels: modus-modal

#2689 Navbar: dropdown allows manual selection
  package-lock.json
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-navbar/dropdown/modus-navbar-dropdown.tsx
  stencil-workspace/src/components/modus-navbar/modus-navbar.models.ts
  stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
Labels: modus-navbar

#2690 Autocomplete: Improve disabled state CSS
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.scss
Labels: bug, modus-autocomplete

#2657 Table: Exposed the placeholder for the select type cells
  stencil-workspace/src/components/modus-table/models/modus-table.models.ts
  stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-editor/modus-table-cell-editor.tsx
  stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-editor/readme.md
Labels: modus-table

#2692 Release v0.34.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#2693 Release v0.34.0 - ng & React
  angular-workspace/ng14/package-lock.json
  angular-workspace/ng14/package.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/package-lock.json
  angular-workspace/ng15/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/package-lock.json
  angular-workspace/ng16/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/package-lock.json
  angular-workspace/ng17/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: skip-changelog

#2714 Modal: Fix for Max-height Issue
  stencil-workspace/src/components/modus-modal/modus-modal.scss
  stencil-workspace/storybook/stories/components/modus-modal/modus-modal-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-modal/modus-modal.stories.tsx
Labels: bug

#2708 Toasts: Updated to Match Figma
  stencil-workspace/src/components/modus-toast/modus-toast.scss
  stencil-workspace/src/components/modus-toast/modus-toast.spec.ts
  stencil-workspace/src/components/modus-toast/modus-toast.tsx
  stencil-workspace/src/components/modus-toast/modus-toast.vars.scss
  stencil-workspace/src/global/themes.scss
  stencil-workspace/src/icons/svgs/icon-info.tsx
  stencil-workspace/storybook/stories/components/modus-toast/modus-toast-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-toast/modus-toast.stories.tsx
Labels: modus-toast

#2724 Alerts: Update Styles
  stencil-workspace/src/components/modus-alert/modus-alert.e2e.ts
  stencil-workspace/src/components/modus-alert/modus-alert.scss
  stencil-workspace/src/components/modus-alert/modus-alert.spec.ts
  stencil-workspace/src/components/modus-alert/modus-alert.tsx
  stencil-workspace/src/components/modus-alert/modus-alert.vars.scss
  stencil-workspace/src/global/modus-variables.scss
  stencil-workspace/src/global/themes.scss
  stencil-workspace/storybook/stories/components/modus-alert/modus-alert-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-alert/modus-alert.stories.tsx
Labels: modus-alert

#2728 StoryBook: Documentation update for react button click
  stencil-workspace/storybook/stories/framework-integrations/react.stories.mdx
Labels: docs

#2731 Release v0.35.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#2735 Release v0.35.0 - ng & React
  angular-workspace/ng14/package-lock.json
  angular-workspace/ng14/package.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/package-lock.json
  angular-workspace/ng15/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/package-lock.json
  angular-workspace/ng16/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/package-lock.json
  angular-workspace/ng17/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
  react-workspace/test-web-components/package-lock.json
  react-workspace/test-web-components/package.json
Labels: skip-changelog

#2736 Updated Instructions "Running the App"
  CONTRIBUTING.md
Labels: docs
