Repository trimble-oss/modus-web-components, pull requests merged in 2024-05, with the labels that each got.

#2447 Blank aria label fixes
  stencil-workspace/src/components/modus-accordion/modus-accordion.e2e.ts
  stencil-workspace/src/components/modus-accordion/modus-accordion.tsx
  stencil-workspace/src/components/modus-alert/modus-alert.e2e.ts
  stencil-workspace/src/components/modus-alert/modus-alert.spec.ts
  stencil-workspace/src/components/modus-alert/modus-alert.tsx
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.e2e.ts
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
  stencil-workspace/src/components/modus-badge/modus-badge.e2e.ts
  stencil-workspace/src/components/modus-badge/modus-badge.tsx
  stencil-workspace/src/components/modus-breadcrumb/modus-breadcrumb.e2e.ts
  stencil-workspace/src/components/modus-breadcrumb/modus-breadcrumb.tsx
  stencil-workspace/src/components/modus-button/modus-button.e2e.ts
  stencil-workspace/src/components/modus-button/modus-button.tsx
  stencil-workspace/src/components/modus-card/modus-card.e2e.ts
  stencil-workspace/src/components/modus-card/modus-card.tsx
  stencil-workspace/src/components/modus-checkbox/modus-checkbox.e2e.ts
  stencil-workspace/src/components/modus-chip/modus-chip.e2e.ts
  stencil-workspace/src/components/modus-chip/modus-chip.tsx
  stencil-workspace/src/components/modus-date-input/modus-date-input.e2e.ts
  stencil-workspace/src/components/modus-date-input/modus-date-input.tsx
  stencil-workspace/src/components/modus-dropdown/modus-dropdown.e2e.ts
  stencil-workspace/src/components/modus-dropdown/modus-dropdown.tsx
  stencil-workspace/src/components/modus-message/modus-message.e2e.ts
  stencil-workspace/src/components/modus-message/modus-message.tsx
  stencil-workspace/src/components/modus-modal/modus-modal.e2e.ts
  stencil-workspace/src/components/modus-modal/modus-modal.tsx
  stencil-workspace/src/components/modus-navbar/modus-navbar.e2e.ts
  stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
  stencil-workspace/src/components/modus-pagination/modus-pagination.e2e.ts
  stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
  stencil-workspace/src/components/modus-select/modus-select.e2e.ts
  stencil-workspace/src/components/modus-select/modus-select.tsx
  stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.e2e.ts
  stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
  stencil-workspace/src/components/modus-slider/modus-slider.e2e.ts
  stencil-workspace/src/components/modus-slider/modus-slider.tsx
  stencil-workspace/src/components/modus-switch/modus-switch.e2e.ts
  stencil-workspace/src/components/modus-switch/modus-switch.tsx
  stencil-workspace/src/components/modus-tabs/modus-tabs.e2e.ts
  stencil-workspace/src/components/modus-tabs/modus-tabs.tsx
  stencil-workspace/src/components/modus-text-input/modus-text-input.e2e.ts
  stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
  stencil-workspace/src/components/modus-time-picker/modus-time-picker.e2e.ts
  stencil-workspace/src/components/modus-time-picker/modus-time-picker.tsx
  stencil-workspace/src/components/modus-toast/modus-toast.e2e.ts
  stencil-workspace/src/components/modus-toast/modus-toast.tsx
  stencil-workspace/src/components/modus-tooltip/modus-tooltip.e2e.ts
  stencil-workspace/src/components/modus-tooltip/modus-tooltip.tsx
Labels: bug, accessibility, modus-input

#2486 Checkbox : Linked checkbox and label for Screen Reader Accessibility
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-checkbox/modus-checkbox.scss
  stencil-workspace/src/components/modus-checkbox/modus-checkbox.spec.tsx
  stencil-workspace/src/components/modus-checkbox/modus-checkbox.tsx
  stencil-workspace/src/components/modus-checkbox/modus-checkbox.vars.scss
  stencil-workspace/src/components/modus-checkbox/readme.md
  stencil-workspace/src/components/modus-content-tree/modus-tree-view-item/modus-tree-view-item.tsx
  stencil-workspace/src/components/modus-dropdown/modus-dropdown.scss
  stencil-workspace/src/global/themes.scss
  stencil-workspace/storybook/stories/components/modus-checkbox/modus-checkbox-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-checkbox/modus-checkbox.stories.tsx
Labels: bug, accessibility

#2508 GitHub Actions Updates
  .github/workflows/axe-linter.yml
  .github/workflows/google-chat-notifiy.yml
  .github/workflows/super-linter.yml
Labels: dependencies, devOps, skip-changelog, github_actions

#2512 Release v0.28.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
  stencil-workspace/src/components.d.ts
Labels: skip-changelog

#2513 Release v0.28.0 - ng & React
  angular-workspace/ng14/package-lock.json
  angular-workspace/ng14/package.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/package-lock.json
  angular-workspace/ng15/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/package-lock.json
  angular-workspace/ng16/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/package-lock.json
  angular-workspace/ng17/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: skip-changelog

#2360 Tabs: make individual tabs buttons
  stencil-workspace/src/components/modus-tabs/modus-tabs.e2e.ts
  stencil-workspace/src/components/modus-tabs/modus-tabs.scss
  stencil-workspace/src/components/modus-tabs/modus-tabs.spec.ts
  stencil-workspace/src/components/modus-tabs/modus-tabs.tsx
Labels: accessibility

#2379 Navbar: Add `aria-label` attribute
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-navbar/modus-navbar.e2e.ts
  stencil-workspace/src/components/modus-navbar/modus-navbar.spec.ts
  stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
  stencil-workspace/src/components/modus-navbar/readme.md
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
Labels: accessibility

#2524 Table: Manual Pagination `currentPagesize` not working on initial load fix
  stencil-workspace/src/components/modus-table/modus-table.core.tsx
  stencil-workspace/src/components/modus-table/modus-table.tsx
Labels: bug, modus-table

#2527 Pagination - Added button to lists
  stencil-workspace/src/components/modus-pagination/modus-pagination.e2e.ts
  stencil-workspace/src/components/modus-pagination/modus-pagination.scss
  stencil-workspace/src/components/modus-pagination/modus-pagination.spec.ts
  stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
  stencil-workspace/src/components/modus-table/modus-table.e2e.ts
Labels: bug, accessibility

#2530 Release v0.29.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
  stencil-workspace/src/components.d.ts
Labels: skip-changelog

#2531 Release v0.29.0 - ng & React
  angular-workspace/ng14/package-lock.json
  angular-workspace/ng14/package.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng14/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng15/package-lock.json
  angular-workspace/ng15/package.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/package-lock.json
  angular-workspace/ng16/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/package-lock.json
  angular-workspace/ng17/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: skip-changelog

#2534 Analytics Update
  .cspell.json
  stencil-workspace/src/index.html
  stencil-workspace/src/sample.html
  stencil-workspace/storybook/.storybook/manager-head.html
Labels: docs

#2533 CodeQL GitHub Action Improvements
  .github/workflows/codeql.yaml
Labels: 1, devOps, github_actions

#2388 File Dropzone: Make message customizable
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-file-dropzone/modus-file-dropzone.spec.ts
  stencil-workspace/src/components/modus-file-dropzone/modus-file-dropzone.tsx
  stencil-workspace/src/components/modus-file-dropzone/readme.md
  stencil-workspace/storybook/stories/components/modus-file-dropzone/modus-file-dropzone-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-file-dropzone/modus-file-dropzone.stories.tsx
Labels: modus-file-dropzone

#2544 Tabs: Add icon support
  stencil-workspace/src/components/modus-tabs/modus-tabs.scss
  stencil-workspace/src/components/modus-tabs/modus-tabs.spec.ts
  stencil-workspace/src/components/modus-tabs/modus-tabs.tsx
  stencil-workspace/storybook/stories/components/modus-tabs/modus-tabs-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-tabs/modus-tabs.stories.tsx
Labels: modus-tabs
