Repository trimble-oss/modus-web-components, pull requests merged in 2025-04, with the labels that each got.

#3256 Release v1.5.1
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#3259 Release v151 ng & react
  .cspell.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
  react-workspace/react-19/package-lock.json
  react-workspace/react-19/package.json
Labels: skip-changelog

#3282 npm audit fix
  .github/dependabot.yml
  react-workspace/test-react-v17/package-lock.json
  react-workspace/test-react-v17/package.json
  react-workspace/test-react-v18/package.json
  react-workspace/test-react-v19/.npmrc
  react-workspace/test-react-v19/package-lock.json
  react-workspace/test-react-v19/package.json
  react-workspace/test-web-components/package-lock.json
  react-workspace/test-web-components/package.json
Labels: dependencies

#3292 Switch to @stencil-community/postcss
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
  stencil-workspace/stencil.config.ts
Labels: dependencies

#3277 Navbar: Fix dropdown UI issues with slots
  stencil-workspace/src/components/modus-dropdown/modus-dropdown.spec.ts
  stencil-workspace/src/components/modus-dropdown/modus-dropdown.tsx
  stencil-workspace/src/components/modus-dropdown/readme.md
  stencil-workspace/src/components/modus-navbar/button-list/modus-navbar-button-list.tsx
  stencil-workspace/src/components/modus-navbar/modus-navbar.scss
Labels: bug

#3297 Stencil Config Update: Add `externalRuntime: false`
  stencil-workspace/stencil.config.ts
Labels: devOps

#3300 Release v160 - ng & react
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
  react-workspace/react-19/package-lock.json
  react-workspace/react-19/package.json
  stencil-workspace/netlify.toml
Labels: skip-changelog
