Repository trimble-oss/modus-web-components, pull requests merged in 2025-03, with the labels that each got.

#3215 Date Picker: remove error message on valid date
  stencil-workspace/src/components/modus-date-picker/modus-date-picker.tsx
Labels: bug

#3219 Prettier Formatting
  sonar-project.properties
  stencil-workspace/netlify.toml
  stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
  stencil-workspace/src/components/modus-content-tree/modus-content-tree.e2e.ts
  stencil-workspace/src/components/modus-content-tree/modus-tree-view/modus-tree-view.tsx
  stencil-workspace/src/components/modus-table/parts/cell/flex-renderer.tsx
  stencil-workspace/src/components/modus-table/parts/modus-table-body.tsx
  stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
  stencil-workspace/storybook/stories/components/modus-accordion/modus-accordion-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-breadcrumb/modus-breadcrumb.stories.tsx
  stencil-workspace/storybook/stories/components/modus-checkbox/modus-checkbox.stories.tsx
  stencil-workspace/storybook/stories/components/modus-chip/modus-chip-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown.stories.tsx
  stencil-workspace/storybook/stories/components/modus-side-navigation/modus-side-navigation-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
Labels: skip-changelog

#3218 Navbar: Added scss selector for external icons
  stencil-workspace/src/components/modus-navbar/modus-navbar.scss
Labels: modus-navbar

#3227 Release v1.5.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#3228 v150 ng & React
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/package-lock.json
  angular-workspace/ng17/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
  react-workspace/react-19/package-lock.json
  react-workspace/react-19/package.json
  react-workspace/test-react-v19/package-lock.json
  react-workspace/test-react-v19/package.json
Labels: skip-changelog

#3241 Angular packages `npm audit fix`
  angular-workspace/ng15/package-lock.json
  angular-workspace/ng15/package.json
  angular-workspace/ng16/package-lock.json
  angular-workspace/ng16/package.json
  angular-workspace/ng17/package-lock.json
  angular-workspace/ng17/package.json
  package.json
Labels: dependencies, security-issue
