Repository trimble-oss/modus-web-components, pull requests merged in 2025-01, with the labels that each got.

#3097 Table: Row action menu only feature
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-list-item/modus-list-item.tsx
  stencil-workspace/src/components/modus-list-item/readme.md
  stencil-workspace/src/components/modus-table/models/modus-table.models.ts
  stencil-workspace/src/components/modus-table/modus-table.tsx
  stencil-workspace/src/components/modus-table/parts/row/actions/modus-table-row-actions-menu/modus-table-row-actions-menu.tsx
  stencil-workspace/storybook/stories/components/modus-list/modus-list-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-list/modus-list.stories.tsx
  stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
  stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
Labels: modus-table

#3125 Fix Security issues
  react-workspace/test-react-v18/package-lock.json
  react-workspace/test-react-v18/package.json
  react-workspace/test-web-components/package-lock.json
  react-workspace/test-web-components/package.json
Labels: dependencies

#3132 Release v1.2.0
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#3134 Release v1.2.0 - ng & React
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
Labels: skip-changelog

#3136 Toasts: Fix for icon-warning not displaying
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-chip/readme.md
  stencil-workspace/src/components/modus-dropdown/readme.md
  stencil-workspace/src/components/modus-icons/readme.md
  stencil-workspace/src/components/modus-table/parts/row/actions/modus-table-row-actions/readme.md
  stencil-workspace/src/components/modus-table/parts/row/actions/readme.md
  stencil-workspace/src/components/modus-table/readme.md
  stencil-workspace/src/components/modus-tooltip/readme.md
  stencil-workspace/src/icons/svgs/icon-warning.tsx
Labels: bug

#3154 Release v130
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#3156 npm audit fix (test-ng15)
  angular-workspace/test-ng15/package-lock.json
  angular-workspace/test-ng15/package.json
Labels: dependencies, skip-changelog, security fix

#3157 Release v130 - ng & React
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
  react-workspace/test-react-v18/.npmrc
  react-workspace/test-react-v18/package-lock.json
  react-workspace/test-react-v18/package.json
Labels: skip-changelog
