Repository trimble-oss/modus-web-components, pull requests merged in 2025-05, with the labels that each got.

#3322 Release v170 ng & react
  .cspell.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng15/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
  react-workspace/react-19/package-lock.json
  react-workspace/react-19/package.json
Labels: skip-changelog

#3336 Markdown lint fixes
  design/capability-design.md
Labels: 1, skip-changelog

#3340 GitHub Action workflow: Adds Angular 19 support
  .github/workflows/publish-angular.yml
Labels: devOps

#3334 Table: Add support for row disabling
  stencil-workspace/src/components.d.ts
  stencil-workspace/src/components/modus-table/models/table-context.models.ts
  stencil-workspace/src/components/modus-table/modus-table.scss
  stencil-workspace/src/components/modus-table/modus-table.tsx
  stencil-workspace/src/components/modus-table/parts/modus-table-body.tsx
  stencil-workspace/src/components/modus-table/parts/row/selection/modus-table-cell-checkbox.tsx
  stencil-workspace/src/components/modus-table/readme.md
  stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
Labels: modus-table

#3346 Release v1.8.0
  .github/copilot-instructions.md
  stencil-workspace/package-lock.json
  stencil-workspace/package.json
Labels: skip-changelog

#3347 Release v1.8.0 - ng & React
  angular-workspace/ng16/.npmrc
  angular-workspace/ng16/package-lock.json
  angular-workspace/ng16/package.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng16/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng17/package-lock.json
  angular-workspace/ng17/package.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng17/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng18/projects/trimble-oss/modus-angular-components/package.json
  angular-workspace/ng19/projects/trimble-oss/modus-angular-components/package-lock.json
  angular-workspace/ng19/projects/trimble-oss/modus-angular-components/package.json
  react-workspace/react-17/package-lock.json
  react-workspace/react-17/package.json
  react-workspace/react-18/package-lock.json
  react-workspace/react-18/package.json
  react-workspace/react-19/package-lock.json
  react-workspace/react-19/package.json
Labels: skip-changelog
